### ISSUE TITLE
Images inside List Item not shown in IA - Missing rule

### ISSUE THREAD

**Issue by luzan** [Automattic/facebook-instant-articles-wp#811] opened 2017-11-10 03:50 UTC
## Steps required to reproduce the problem

1. WordPress with BuzzBlog Theme 
2. Insert images in articles inside List item. (Not featured image)

## Expected Result
I was expecting to see images in IA via Facebook Page Manager App. 
BTW, when I submitted IA for Review, I also got message including.

> It looks like some of your articles are missing one or more of the following items: text, and/or embeds and/or media elements (images/video) from the web version of the article.

## Actual Result 

When I then checked into those articles from Facebook Page Manager App, I realized that there were no images.
Yet there are also some Warnings on WordPress post. 
![iaerror](https://user-images.githubusercontent.com/3870422/32641970-2fe898ce-c5f9-11e7-89aa-e2a3f8484004.PNG)

Here are
Source Markup
https://gist.github.com/anonymous/b7acde2d50737d8a945506e08beb6f81

Transformed Markup
https://gist.github.com/luzan/3c8008f80d42b39dee964983ff49ed02

## Version Info

* Plugin version: 4.0.5
* WordPress version: 4.8.3
* PHP version: 5.6.30

**Comment by pestevez** [comment] 2017-11-10 14:27
Duplicate of #803, #723 for the images inside `<li>` issue. Please check the solutions provided there as workarounds. In short, the Instant Articles format does not support images as children of list items. The warnings you are getting are the reason they are not getting to the Instant Articles markup, but you can get rid of them using the rules in the referenced issues.

**Comment by pestevez** [comment] 2017-11-10 14:31
Hey @luzan, while we don't officially support compatibility with BuzzBlog, I believe you can achieve your goal with the rules described in the linked issues in my previous comment.

If you'd like the plugin to be compatible with BuzzBlog please submit a separate feature request issue, which our team can prioritize, or you can submit a PR adding the support.

I am closing this issue now, but please feel free to reopen if you need additional information. Thanks

**Closed by pestevez** 2017-11-10 14:31 UTC
Labels: missing rule
