### ISSUE TITLE
Featured image VS og image

### ISSUE THREAD

**Issue by imidazil** [Automattic/facebook-instant-articles-wp#816] opened 2017-11-13 13:20 UTC
## Steps required to reproduce the problem

1. create new post and add featured image
2. add facebook image (og image) with Yoast SEO plugin
3. click publish
4. share on facebook

## Expected Result

featured image

## Actual Result 

facebook open graph image

## Version Info

* Plugin version: 4.8.3
* WordPress version: 4.8.5
* PHP version: 5.6.32

**Comment by diegoquinteiro** [comment] 2017-11-15 20:54
Hi @imidazil, thanks for reporting!

We always pull the featured image from WordPress to be the cover image on the Instant Articles. If you do use a plugin to provide a og:image, we'll not pull from there - in fact you might want to use different images to be the og:image and the article cover.

Closing as this is the expected behavior by design. Please reopen if you have more questions!

**Closed by diegoquinteiro** 2017-11-15 20:54 UTC
