### ISSUE TITLE
i am using wordpress and instant article for wordpress plugin but from yesterday it's not transforming the posts in instant article..

### ISSUE THREAD

**Issue by Suraj13upadhyay** [Automattic/facebook-instant-articles-wp#804] opened 2017-11-05 14:46 UTC

**Comment by pestevez** [comment] 2017-11-06 18:25
Can you please post the version of the plugin you are using, the version of WordPress you are using, and the steps to reproduce the issue?

Also, do you see any error message at the bottom of the post editing page? There should be a section called `Facebook Instant Articles`:

![image](https://user-images.githubusercontent.com/18663703/32457128-ee2fbdc8-c2f5-11e7-8a0f-752174c32582.png)

**Comment by WadhawanAvinash** [comment] 2017-11-06 19:08
I'm having the same issue.

**Comment by WadhawanAvinash** [comment] 2017-11-06 19:19
Wordpress Version - 4.8.3
Instant Articles Plugin Version - 4.0.5
There are no error messages at the bottom & it is perfectly showing HTML below. The problem is it is not submitting them to Production Article section at Facebook.

**Comment by pestevez** [comment] 2017-11-06 19:35
Thanks, @WadhawanAvinash. Have you shared a link to the article on Facebook yet? This version of the plugin will not create the Instant Article immediately. Instead, it will create it the first time the article link is shared. That could be the reason why you are not seeing the article under the Production Articles section.

If you want to check the Instant Article before sharing the link, you can trigger a scrape manually using the [Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/). Just pass the URL of your article.

If the solution described above does not work, can you please share the link to any of the articles you are having issues with?

Also, can you check if you have **Development Mode** enabled? You can check it under the plugin settings:

![image](https://user-images.githubusercontent.com/18663703/32459481-d873c102-c2fd-11e7-9418-a6bd11104ea2.png)

**Comment by WadhawanAvinash** [comment] 2017-11-07 18:09
By enabling Development Mode, all articles moving to Development Articles with status as Unpublished. How those can be moved into Production Articles as before.

**Comment by pestevez** [comment] 2017-11-08 01:17
You will have to disable the Development mode, save the settings, and Update all the posts you want to move their corresponding Instant Articles from Development to Production. That will ensure your posts' HTML markup has the meta tag `ia:markup_url` that will send them to the Production feed once scrapped.

**Comment by WadhawanAvinash** [comment] 2017-11-08 19:08
Thanks a lot it worked for now. 

But the problem is that why it is not submitting automatically when I'm publishing a new article.

**Comment by pestevez** [comment] 2017-11-08 19:12
Event after you share the link to the Article on Facebook OR trigger a manual scrape of the article's URL using the [Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/)?

If the solution described above does not work, can you please share the link to any of the articles you are having issues with?

**Comment by pestevez** [comment] 2017-11-10 19:55
I am closing the issue now. Please feel free to reopen if you need additional information.

**Closed by pestevez** 2017-11-10 19:55 UTC
Labels: more info needed

**Comment by tinwinswe** [comment] 2018-11-17 04:11
I also can not activate instant article for wp on my word press. It has error message like this.
Parse error: syntax error, unexpected '[' in /home/content/07/10034407/html/hklatyar/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 108

what can i do for that.

**Comment by tinwinswe** [comment] 2018-11-17 04:18
I also can not activate my instant article wp on my word press, it has error like this.
Parse error: syntax error, unexpected '[' in /home/content/07/10034407/html/hklatyar/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 108

Instant Articles for WP version 4.1.1
wordpress latest version
thank you
