### ISSUE TITLE
Text Characters >,<, & (HTML &lt; &gt;  and &amp;) do not convert

### ISSUE THREAD

**Issue by SeanWP** [Automattic/facebook-instant-articles-wp#903] opened 2018-03-13 17:03 UTC
## Steps required to reproduce the problem

1.  Text characters >, <, and & convert to "& lt;" "& gt;"  and "& amp;" in html.
2.  Plugin does not convert  "& lt;" "& gt;"  and "& amp;"  to text symbols in FBIA markup.
3.  Is there a way to create a transformer rule to replace "& lt;" "& gt;"  and `"& amp;"` with the corresponding text symbols, or alternatively, the text "less than" "greater than" and "and"? Space intentionally left between characters and ampersand symbol because the github comment box converts the html to text symbols.

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.06
* WordPress version: 4.94
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by timjacobi** [comment] 2018-03-29 11:16
duplicate of #881

**Closed by timjacobi** 2018-03-29 11:16 UTC
Labels: bug, help wanted
