### ISSUE TITLE
Undefined property: Instant_Articles_Post::$post in version 4.0.0

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/facebook-instant-articles-wp#703] opened 2017-06-28 04:27 UTC
Just installed version 4.0.0 of the Instant Articles plugin.

The plugin is throwing these PHP notices on every page load

Undefined property: Instant_Articles_Post::$post

This is coming from this line of code:
wp-content/plugins/fb-instant-articles/class-instant-articles-post.php:887

And the call stack looks like this.
```
Instant_Articles_Post->should_submit_post()
wp-content/plugins/fb-instant-articles/facebook-instant-articles.php:369
inject_ia_markup_meta_tag()
wp-includes/class-wp-hook.php:298
do_action('wp_head')
wp-includes/general-template.php:2589
wp_head()
wp-content/themes/mysite/templates/head.php:34
load_template('~/wp-content/themes/mysite/templates/head.php')
wp-includes/template.php:647
locate_template()
wp-includes/general-template.php:167
get_template_part('templates/head')
wp-content/themes/mysite/base.php:19
```

**Comment by vkama** [comment] 2017-06-28 14:28
Hey Kevin, thanks for the report.

I think I found the problem in the code but I am having trouble reproducing the bug, which is weird because the code looks broken.

What PHP version are you using?

**Comment by kevinlisota** [comment] 2017-06-28 16:03
PHP 7.1.5

**Comment by diegoquinteiro** [comment] 2017-06-28 19:49
Hey,

That should be fixed on v4.0.1 we've just launched, can you confirm @kevinlisota ? 

Re-open the issue otherwise!

Thanks!
Diego

**Closed by diegoquinteiro** 2017-06-28 19:49 UTC
Labels: bug

**Comment by kevinlisota** [comment] 2017-06-28 23:21
@diegoquinteiro indeed, this is fixed now. I see the ia:markup_url meta tag appearing as well.

Out of curiosity, what is the purpose of that meta tag? I am not finding documentation of it.

**Comment by diegoquinteiro** [comment] 2017-06-30 23:14
Hi @kevinlisota,

We're missing this documentation for now, but I'll put it on our developers portal soon. Basically that's the tag that tells Facebook Crawler to ingest the Instant Article.

We're not using the API endpoints anymore, this tag is all you need for ingesting articles now, which led to a massive simplification of the plugin and should bring more stability over time.

Thanks,
Diego
