### ISSUE TITLE
Trigger (not set) and not found in GA

### ISSUE THREAD

**Issue by CarsonLee27** [Automattic/facebook-instant-articles-wp#104] opened 2016-04-12 09:08 UTC
Have insert the GA code to the Embed code part and found that having this issue. 

![screen shot 2016-04-12 at 5 03 09 pm](https://cloud.githubusercontent.com/assets/4049250/14455192/d25b53f2-00d0-11e6-8f61-bb377bfa32b9.png)

![screen shot 2016-04-12 at 5 07 42 pm](https://cloud.githubusercontent.com/assets/4049250/14455236/178c10e2-00d1-11e6-8406-a79bdb9f88e3.png)

**Comment by demoive** [comment] 2016-04-12 09:15
Hi, @CarsonLee27. Thanks for the feedback. Could you provide some more information about the issue you're having? For example, the embed code you're using and perhaps also more information about where the screenshot is from or what it is indicating?

I'm unclear where you placed your embed code. Did you copy and paste it in to text box in the settings of the plugin?

**Comment by CarsonLee27** [comment] 2016-04-12 09:27
Sorry, my bad. Not sure what kind of info shall I provide more. Let me know if the info below is not enough xD Appreciate. 

The above screenshot is from Google Analytics. 
After we publish the article (LIVE instant article), then the GA start appearing to have the above screenshot I shared. (not set for title) and not found with the URL /instant_article/tracker. 
Wondering which source can direct user to /instant_article/tracker/......

Yes. I did place the GA to the Embed section. 

<img width="1163" alt="screen shot 2016-04-12 at 5 19 09 pm" src="https://cloud.githubusercontent.com/assets/4049250/14455640/1d51c2ea-00d3-11e6-8a0e-7723d929aea9.png">

**Comment by diegoquinteiro** [comment] 2016-04-12 21:55
CarsonLee27 you can, instead, install Google Analytics for WP by Yoast plugin, which is compatible with ours. Then you come back to this screen you printed, disable your custom code and enable the plugin integration.

**Comment by CarsonLee27** [comment] 2016-04-13 03:14
Okay which mean I shall remove the GA code from the website and the plugin right? =D

**Comment by diegoquinteiro** [comment] 2016-04-13 03:20
Yes, use the plugin and let me know if that works!

**Comment by CarsonLee27** [comment] 2016-04-13 03:41
Erm, tried, not really. I still see the (not set) in the title. Still observing as the team are creating content xD

**Comment by CarsonLee27** [comment] 2016-04-13 06:58
@diegoquinteiro seem like still the same =(

**Comment by demoive** [comment] 2016-05-20 11:15
@CarsonLee27 we have not been able to reproduce this problem so I'm marking it as closed for now. Also to note: while #127 isn't directly related to this issue, since it was opened at the same time and has since been resolved with recent updates to the plugins, perhaps this too has been resolved?

**Closed** 2016-05-20 12:24 UTC

**Comment by CarsonLee27** [comment] 2016-05-20 12:31
I have checked lately also. This issue still occurs.
