### ISSUE TITLE
No rules defined for <div class="wp-caption aligncenter"> in the context of InstantArticle

### ISSUE THREAD

**Issue by thenerdstash** [Automattic/facebook-instant-articles-wp#676] opened 2017-05-16 01:12 UTC
I am new to Facebook Instant Articles and my site is on WordPress. I have followed and setup all the proper steps with no problems but now get common errors like No rules defined for <div class="wp-caption aligncenter"> in the context of InstantArticle on my WordPress inside of articles posted. All we are doing is taking images, making them centered, and a caption below that in bold. Can someone please help me correct this and what the proper custom rule needs to be? I would be in your debt!

**Comment by DrLightman** [comment] 2017-05-16 16:30
You may want to "Enable custom transformer rules" and add tell the plugin to ignore or passthrough that tag:

to ignore:

{
    "rules":
    [
    {
        "class": "IgnoreRule",
        "selector" : ".wp-caption.aligncenter"
    }
  ]
}

or to passthrough:

{
    "rules":
    [
    {
        "class": "PassThroughRule",
        "selector" : ".wp-caption.aligncenter"
    }
  ]
}

If I remember correctly, ignore will strip the whole selected elements and innerhtml whereas passthrough will only strip the html tag, but I'm not 100% sure, try them both separately eventually.

**Comment by colinhowells** [comment] 2017-06-07 22:04
If anyone involved with the plugin isn't aware, captions - which create a wrapping div with a class of .wp-caption around the image and caption text, usually with a hardcoded width - are an _extremely_ common use case, and should be supported. I was very surprised to find that they are still being stripped by default.

Thanks to @finalhit who a year ago [created this helpful ruleset](https://github.com/Automattic/facebook-instant-articles-wp/issues/205#issuecomment-220780141) for people to pop in the 'Custom transformer rules' in Advanced Settings in the plugin admin screen:

`{"rules": [ { "class": "CaptionRule", "selector" : "p.wp-caption-text" }, { "class": "ImageRule", "selector" : "div.wp-caption", "properties" : { "image.url" : { "type" : "string", "selector" : "img", "attribute": "src" }, "image.caption" : { "type" : "element", "selector" : "p.wp-caption-text" } } } ]}`

This aside, the plugin's working well for me and I appreciate the work that went into this. Parsing somebody else's markup, especially potentially arbitrary markup, is no trivial thing!

**Comment by colinhowells** [comment] 2017-06-07 22:51
Speaking to the OP's initial question: IA by design is stripping down your markup to a small subset of what is possible in HTML. A lot of what you typically do in terms of layout within your pages in WP will intentionally disappear. In much the same way the styling (bolding, colors, fonts) that you would normally do with CSS is also gone, in favor of selecting a few options within your IA configuration in the FB page that's publishing these posts.

Image centering wouldn't really have applicability here, because IA is targeting a narrow viewport. Afaik there isn't really a way to 'center' images, just as there isn't a way to float left or right.

The bolding of the caption text you could do in the styles set for IA itself, either by editing the styles in the configuration tab of the FB page's IA settings (watch the background colors when you do edit text colors, the default backgrounds will switch to an electric blue and you'll have to reset them to what's desired) or by setting that style within the admin screen of the IA plugin in your WP back end.

**Comment by timjacobi** [comment] 2017-10-03 15:19
Duplicate of #582

Please continue the discussion there.

**Closed by timjacobi** 2017-10-03 15:19 UTC
