### ISSUE TITLE
No rules defined for <div> in the context of InstantArticle 

### ISSUE THREAD

**Issue by codeslane** [Automattic/facebook-instant-articles-wp#727] opened 2017-07-14 18:44 UTC
No rules defined for <div> in the context of InstantArticle
No rules defined for <img class=" wp-image-1031 aligncenter"> in the context of Anchor

I'm getting these two errors.
images and gifs aren't loading

please solve.

here the information 

Source 👍 
<h1>What is Unrequited Love?</h1>
<p><em>Unrequited Love, The word itself is enough to give chills, isn’t it? </em><em>Unrequited Love or One-sided Love – kind of love where you are not loved back or your love is not understood by your beloved.</em></p>
<p><em>Your beloved may or may not be aware of your deep and strong affection, or might even reject it.</em></p>
<p><em>This is what it sounds like.</em></p>
<p>I guess, everyone has seen that Bollywood movie glorifying <em>“</em>Ektarfa<em> Pyaar Ki </em>taakat<em>”</em>. They showed how your Ektarfa Pyaar will knock you down to your knees and you’ll end up becoming an overnight star. They even showed you how even after a heartbreak you’ll attend your beloved’s wedding.</p>
<p><em>But, How many of us are going to do this or did this? None of us, you read it right None of us.</em></p>
<p><em>Just for the reality check Darling, nothing like that is going to ever happen.</em> The reality of unrequited love y<em>ou’ll experience both the gift &amp; curse LONELINESS.</em></p>
<p><em>SELF DOUBT is your bae now.</em></p>
<p><em>HEARTACHE Your second home now.</em></p>
<p><em>It seems like the worst possible experience. Isn’t it so?</em></p>
<p><em>But, here’s the twist it is not the worst possible experience. It might appear like the worst thing but it will change your life forever, that too for all the good reason.</em></p>
<p><em>Yeah, it will change your life forever, even though it doesn’t feel like right now.</em></p>
<p><em>Assuming that you’re experiencing the worst possible story right now of your UNREQUITED LOVE. I wish you all the luck to make the best or the worst out of that experience.</em></p>
<div style="width: 100%; height: 0; padding-bottom: 56%; position: relative;"><iframe class="giphy-embed" style="position: absolute;" src="https://giphy.com/embed/ZVfhlEEGbwuFG" width="100%" height="100%" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>
<h2>Benefits of Unrequited Love</h2>
<p>I’ll directly jump onto the benefits you’ll reap after the season of One-sided love.</p>
<h3><em>Here’s what will happen to you:</em></h3>
<p><em>One day you’ll get up and suddenly realize what you’ve gone through is really painful and heartbreaking but, for all the good reasons you’ll decide to stop this experience right at the moment.</em></p>
<ul>
<li>You’ll know what you’ve gone through is totally worth it, since You came out as a better version of yourself.</li>
<li>It’ll make you think What you want? And not what the admirer of your beloved want.</li>
<li>You will question yourself Why you feel the way you do? After the session of questioning yourself numerous of times, after perceiving things as it is, you’ll realize What you want is the idea of them and not actually them.</li>
<li>You’ll learn what it means to love again for all the good reasons.</li>
<li>You won’t have to wonder anymore if you’re dealing with Love or Lust – you’ll know.</li>
<li>You will force yourself to improve – sounds known! Yeah, you’ve forced yourself initially for them but, now you’ll do it to experience a much better version of yourself.</li>
<li>You’ll get to know yourself well, really well.</li>
<li>You will immerse yourself in Yourself, your hobbies, your best friends, your family, and your career.</li>
</ul>
<p>&nbsp;</p>
<h2>Finally, You’ll realize the remote of your Happiness is in your Hand.<a href="https://www.codeslane.com/content/uploads/2017/07/635867833173741071-2054119491_Happiness-is-a-choice-lifepopper-words-of-wisdom-how-to-live-a-happy-life-stay-positive-smile-1.jpg"><img class=" wp-image-1031 aligncenter" src="https://www.codeslane.com/content/uploads/2017/07/635867833173741071-2054119491_Happiness-is-a-choice-lifepopper-words-of-wisdom-how-to-live-a-happy-life-stay-positive-smile-1.jpg" alt="Happiness, love" width="666" height="333" srcset="https://www.codeslane.com/content/uploads/2017/07/635867833173741071-2054119491_Happiness-is-a-choice-lifepopper-words-of-wisdom-how-to-live-a-happy-life-stay-positive-smile-1.jpg 2000w, https://www.codeslane.com/content/uploads/2017/07/635867833173741071-2054119491_Happiness-is-a-choice-lifepopper-words-of-wisdom-how-to-live-a-happy-life-stay-positive-smile-1-300x150.jpg 300w, https://www.codeslane.com/content/uploads/2017/07/635867833173741071-2054119491_Happiness-is-a-choice-lifepopper-words-of-wisdom-how-to-live-a-happy-life-stay-positive-smile-1-768x384.jpg 768w, https://www.codeslane.com/content/uploads/2017/07/635867833173741071-2054119491_Happiness-is-a-choice-lifepopper-words-of-wisdom-how-to-live-a-happy-life-stay-positive-smile-1-1024x512.jpg 1024w" sizes="(max-width: 666px) 100vw, 666px" /></a></h2>
<blockquote><p><em>You will not take anything for granted, not even your heartache.</em></p>
<p><em>You’ll find yourself giving your best to all the other relationships of your life.</em><br />
<em>You will gather all your broken pieces and will create a masterpiece of it.</em><br />
<em>You’ll get over your limiting belief and find that You, yes You can love again.</em><br />
<em>You will learn to love safely from a Distance. At the end, You will find yourself as nothing else but Confident and Self-reliant than ever before.</em><br />
<em>Know that You deserve all the happiness of the world because:</em><br />
<strong><em>YOU LOVED, YOU LOST and YOU SURVIVED.</em></strong></p></blockquote>

Transformed Markeup : 

<html>
  <head>
    <link rel="canonical" href="https://www.codeslane.com/relationships/unrequited-love-love-trend/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.1"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.2"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.1"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="https://www.codeslane.com/content/uploads/2017/07/vector-love-cartoon-wallpaper_1920x1200_88444.jpg"/>
        </figure>
        <h1>Unrequited Love | Love In Trend</h1>
        <time class="op-published" datetime="2017-07-13T14:12:54+00:00">July 13th, 2:12pm</time>
        <time class="op-modified" datetime="2017-07-14T23:06:05+00:00">July 14th, 11:06pm</time>
        <address><a href="https://www.codeslane.com">Sakshi Jha</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=1556594651022751_1556594751022741&amp;adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <h1>What is Unrequited Love?</h1>
      <p>
        <i>Unrequited Love, The word itself is enough to give chills, isn’t it? </i>
        <i>Unrequited Love or One-sided Love – kind of love where you are not loved back or your love is not understood by your beloved.</i>
      </p>
      <p>
        <i>Your beloved may or may not be aware of your deep and strong affection, or might even reject it.</i>
      </p>
      <p>
        <i>This is what it sounds like.</i>
      </p>
      <p>I guess, everyone has seen that Bollywood movie glorifying <i>“</i>Ektarfa<i> Pyaar Ki </i>taakat<i>”</i>. They showed how your Ektarfa Pyaar will knock you down to your knees and you’ll end up becoming an overnight star. They even showed you how even after a heartbreak you’ll attend your beloved’s wedding.</p>
      <p>
        <i>But, How many of us are going to do this or did this? None of us, you read it right None of us.</i>
      </p>
      <p><i>Just for the reality check Darling, nothing like that is going to ever happen.</i> The reality of unrequited love y<i>ou’ll experience both the gift &amp; curse LONELINESS.</i></p>
      <p>
        <i>SELF DOUBT is your bae now.</i>
      </p>
      <p>
        <i>HEARTACHE Your second home now.</i>
      </p>
      <p>
        <i>It seems like the worst possible experience. Isn’t it so?</i>
      </p>
      <p>
        <i>But, here’s the twist it is not the worst possible experience. It might appear like the worst thing but it will change your life forever, that too for all the good reason.</i>
      </p>
      <p>
        <i>Yeah, it will change your life forever, even though it doesn’t feel like right now.</i>
      </p>
      <p>
        <i>Assuming that you’re experiencing the worst possible story right now of your UNREQUITED LOVE. I wish you all the luck to make the best or the worst out of that experience.</i>
      </p>
      <h2>Benefits of Unrequited Love</h2>
      <p>I’ll directly jump onto the benefits you’ll reap after the season of One-sided love.</p>
      <h2>
        <i>Here’s what will happen to you:</i>
      </h2>
      <p>
        <i>One day you’ll get up and suddenly realize what you’ve gone through is really painful and heartbreaking but, for all the good reasons you’ll decide to stop this experience right at the moment.</i>
      </p>
      <ul>
        <li>You’ll know what you’ve gone through is totally worth it, since You came out as a better version of yourself.</li>
        <li>It’ll make you think What you want? And not what the admirer of your beloved want.</li>
        <li>You will question yourself Why you feel the way you do? After the session of questioning yourself numerous of times, after perceiving things as it is, you’ll realize What you want is the idea of them and not actually them.</li>
        <li>You’ll learn what it means to love again for all the good reasons.</li>
        <li>You won’t have to wonder anymore if you’re dealing with Love or Lust – you’ll know.</li>
        <li>You will force yourself to improve – sounds known! Yeah, you’ve forced yourself initially for them but, now you’ll do it to experience a much better version of yourself.</li>
        <li>You’ll get to know yourself well, really well.</li>
        <li>You will immerse yourself in Yourself, your hobbies, your best friends, your family, and your career.</li>
      </ul>
      <p> </p>
      <h2>Finally, You’ll realize the remote of your Happiness is in your Hand.<a href="https://www.codeslane.com/content/uploads/2017/07/635867833173741071-2054119491_Happiness-is-a-choice-lifepopper-words-of-wisdom-how-to-live-a-happy-life-stay-positive-smile-1.jpg"></a></h2>
      <blockquote><i>You will not take anything for granted, not even your heartache.</i>
<i>You’ll find yourself giving your best to all the other relationships of your life.</i><br/><i>You will gather all your broken pieces and will create a masterpiece of it.</i><br/><i>You’ll get over your limiting belief and find that You, yes You can love again.</i><br/><i>You will learn to love safely from a Distance. At the end, You will find yourself as nothing else but Confident and Self-reliant than ever before.</i><br/><i>Know that You deserve all the happiness of the world because:</i><br/><b><i>YOU LOVED, YOU LOST and YOU SURVIVED.</i></b></blockquote>
      <figure class="op-tracker">
        <iframe>
          <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-89091486-4', 'auto');
  ga('send', 'pageview');
</script>
        </iframe>
      </figure>
      <footer>
        <small>© Codes Inc. All Rights Reserved 2017</small>
      </footer>
    </article>
  </body>
</html>

**Comment by timjacobi** [comment] 2017-10-03 15:18
Duplicate of #582

Please continue the discussion there.

**Closed by timjacobi** 2017-10-03 15:18 UTC
