### ISSUE TITLE
Issue with text going under the feature image of instant articles

### ISSUE THREAD

**Issue by mxmkmarquette** [Automattic/facebook-instant-articles-wp#432] opened 2016-09-01 17:00 UTC
# Steps required to reproduce the problem
1. Create an instant article
   Before the update of this morning everything were going great...
# Expected Result
- text going under the instant article thumbnail
# Actual Result
- look at the screen
  ![img_1322](https://cloud.githubusercontent.com/assets/21690761/18176524/f30fb092-7043-11e6-97f0-ac30eded1a50.PNG)
  ![img_1321](https://cloud.githubusercontent.com/assets/21690761/18176525/f3192c1c-7043-11e6-8d81-7b9663e6df04.PNG)

---

*\* Version Info **
- Plugin version: 3.1.2
- WordPress version: 4.6
- PHP version: 5.6

**Comment by diegoquinteiro** [comment] 2016-12-22 05:42
Closing as this is not a bug with the plugin, instead it might be a bug on Instant Articles. Does it still happen?

**Closed by diegoquinteiro** 2016-12-22 05:42 UTC
