### ISSUE TITLE
Visual composer

### ISSUE THREAD

**Issue by fabiograsso** [Automattic/facebook-instant-articles-wp#322] opened 2016-06-15 12:14 UTC
Hello,
I'm using [Visual Composer](http://codecanyon.net/item/visual-composer-page-builder-for-wordpress/242431), and I've found that articles write with Visual Composer are not rendered.
In particular all the text managed by visual composer is missing in IA feed.

Visual Composer generate text using tag like: [vc_row full_width="" full_screen=""][vc_column][vc_column_text]....[/vc_column_text][/vc_column][/vc_row]

Do you have any suggestion on how to manage this in Instant Articles?

Moreover is it possible to disable IA on determinate taxonomies?

Thanks
Fabio

# Steps required to reproduce the problem

1. Generate a post with Visual Composer
2. Open the generated IA feed
3. 

# Expected Result

* Text of the post present in the feed

# Actual Result

* Text of the post missing in the feed

---

** Version Info **

* Plugin version: 2.1.1
* WordPress version: 4.5.2
* PHP version: 7.0.7

**Comment by everton-rosario** [comment] 2016-07-01 15:24
@fabiograsso This kind of plugin (Visual Composer) isn't supported by our Instant Articles plugin out of the box.

But you can change the hook, to transform the content after "visual composer" translates its short-code into HTML code, then you can hook the Transformer (from our PHP-SDK).

Have you tried this?

Im closing for now, let us know if this still reproduces. Fill in another task or reopen this same one.

Thanks for using Instant Articles.

**Closed by everton-rosario** 2016-07-01 15:24 UTC
Labels: compat, question

**Comment by YYAngel** [comment] 2016-08-22 12:41
Hi guys,

I'm having the same issue.
I'm using Version 3.0.1 of the plugin, Wordpress 4.5.2 and Visual Composer v.4.12

Facebook disapproved my application because of the following reason:

It looks like one or more of your articles are incomplete. Your Instant Article shouldn't be a partial or preview version of the full article. Please make sure the articles in your feed contain all content found in the web versions._ 

There isn't any issue with the content (single post pages) when browsed on desktop or on mobile devices using Safari, Chrome, Firefox, but the image sample with Instant Article preview provided by Facebook doesn't show the content of the articles.
It shows only the logo of the site, categories associated with the article, author, date, share button, part of the preview of related articles (which is the end of a single post page), and that's it. No image, no text.


![facebook-instant-articles-preview](https://cloud.githubusercontent.com/assets/21171310/17854989/c4656204-687e-11e6-86fa-864299766fa6.png)


There is also the following message provided (for a single post page):
General Errors: Empty Articles: You have one or more articles without any content.


![demo-instant-articles](https://cloud.githubusercontent.com/assets/21171310/17854544/23760814-687c-11e6-9416-9aa9d2cf0534.png)


@everton-rosario  If your "fix" works, would you please share a more detailed advice on how to implement it? 

Any help on how to solve this is much appreciated.

Cheers, 
Angel

**Comment by Nmidia** [comment] 2016-09-08 07:06
HI,

Can anyone provide more details on how to do this?

**Comment by abrambailey** [comment] 2016-11-07 05:24
Would love to know the fix. Thank you.

**Comment by antoineroffler** [comment] 2017-01-20 12:47
Can we re-open this ? Or at least post some solutions to the problem ? This issue is talked about all over the wordpress-sphere, you guys should not ignore it

**Comment by Jany-M** [comment] 2017-08-10 14:49
@everton-rosario 
> But you can change the hook, to transform the content after "visual composer" translates its short-code into HTML code, then you can hook the Transformer (from our PHP-SDK).

Thank you for the input, but a little vague, could you please articulate? Thank you

**Comment by texas-ranger** [comment] 2017-08-28 17:39
Hey there, this is my actual solve for this problem.

You can do something like this in your theme function.php
`add_filter('instant_articles_content', function(){
	global $post;
	WPBMap::addAllMappedShortcodes();
	$content = apply_filters( 'the_content', $post->post_content );
	return $content;
});`

you shouldn't forget to add custom transformation rules. I am using something like this
`{ 
    "rules": [
        { "class": "IgnoreRule", "selector": "div.grid-sizer" },
        { "class": "PassThroughRule", "selector": "div[class^='wpb']" },
        { "class": "PassThroughRule", "selector": "div[class^='vc']" }
    ] 
}`

**Comment by arttitorres** [comment] 2017-12-21 22:34
Any plugin like galleries or composer works with Instant Articles. I'm using the visual composer but only displays code lines.
I want to show photo galleries in a widget or plugin. Would you know what can I use to display them on Instant Articles? Any plugin is accepted by Instant Articles?
