### ISSUE TITLE
FB Feedback Many Issues

### ISSUE THREAD

**Issue by OPPtester** [Automattic/facebook-instant-articles-wp#144] opened 2016-04-14 13:22 UTC
I see the FB feedback now, missing content, logo etc 

Some issues I can probably take care of myself such as the style, but missing logo will need a custom code as my site does not use an image for the logo, just a span class. is there a way to target instant articles in my functions.php file to set a logo?

Most of the issue relate to issue [#19](https://github.com/Automattic/facebook-instant-articles-wp/issues/19) 

Here's their feedback:

Our review team examined a sample of your articles and found some problems
Please address these issues before submitting again

Missing content - text elementsSee 2 examples
Missing content - embeds/mediaSee 10 examples
Incorrect Style formattingSee 9 examples
Missing content - byline elementsSee 10 examples

**Comment by diegoquinteiro** [comment] 2016-04-14 18:10
Hi, @OPPtester. Thanks for the feedback.

Could you provide some more information about the issue you're having? That will help us reproduce the issue.

- What version of the plugin are you using?
- What version of WordPress are you using?
- What version of PHP are you using (if known)?
- What's the debug output shown in the post edit screen on the Facebook Instant Article box (both sides)?

Thanks again!

**Comment by OPPtester** [comment] 2016-04-14 20:14
Hi Diego,

Here are the answers best I could:
- Plugin version 2.7 
- WP was 4.4.2 and upgraded last night to 4.5. I think FB looked at them under 4.4.2
- PHP is 5.5.33
- Debug output from the edit screen on FB IA as follows:

1- Missing content - text elements
Basically the web post had an H4 heading, but was omitted in the IA post, the edit/debug shows a regular post no errors.
Some of your articles are missing words or pieces of text that are found in the web versions. Some common omissions include:
Kickers
Subtitles
Captions/Credits
Video controls

FB edit side shows no errors just regular source.

2- Missing content - embeds/media
Issue 1 is every article is missing a logo. This I can take care of by uploading a logo images. They also say:
One or more of your articles are missing social embeds and/or some media elements (images/video).
We support a wide range of social embeds and you can find out how to use them here. I think they mean the share buttons, the web post has share buttons top and bottom of the article.

No errors the edit shows regular source.

3- Missing content - byline elements
The author's name is in every single article. If the author's name appears online, it should be on the Instant Article.

The FB edit side:

<h1>Tesla Motors Inc and Switch Partner for Competitive Electricity Market in Nevada</h1><time class="op-published" datetime="2016-03-26T08:50:21+00:00">March 26th, 8:50am</time><time class="op-modified" datetime="2016-04-12T21:08:17+00:00">April 12th, 9:08pm</time><h3 class="op-kicker">Business</h3><figure class="op-ad"><iframe src="https://www.facebook.com/adnw_request?placement=600903770074192_600942486736987&amp;adtype=banner320x50" width="320" height="50"></iframe></figure></header>

Should be: By <author name> - March 26, 2016

- Other complaints I can take care of such as styling

Please let me know if you need anything to help in this process.

Regards,

**Comment by diegoquinteiro** [comment] 2016-04-14 21:24
Hi @OPPtester,

Thanks for all the info.

I can confirm Author and H4 issues were fixed in 2.7 and converted to H2. About the social embeds, do you have any video/post embed missing on the Instant Article version?

Please keep an eye open for issues as they appear on your WordPress when you save a post, on the bottom of the screen.

**Comment by OPPtester** [comment] 2016-04-14 21:41
Thanks,

I will revisit and check the author/H4 issue as i do have 2.7. I hardly have any video/post embeds in my web posts anyway so couldn't tell.

What I saw this morning is the multiple instances of each post that was published today, I opened [#39](https://github.com/Automattic/facebook-instant-articles-wp/issues/139) for it.

**Comment by OPPtester** [comment] 2016-04-14 23:45
Thanks, I see the author and H4 are taken care of, nice work!

Logo should not be an issue anymore I was able to upload and looks good.

**Comment by demoive** [comment] 2016-05-06 11:39
@OPPtester, the message you reported related to missing embeds/media should be more informational than an error:

> One or more of your articles are missing social embeds and/or some media elements (images/video). We support a wide range of social embeds and you can find out how to use them here. I think they mean the share buttons, the web post has share buttons top and bottom of the article.

If, when you find articles of yours which *do* have media, you don't see them appearing with the generated Instant Article, the problem is most likely related to the Transformer of the plugin not recognizing specific markup within your content (context: our plugin makes use of the [Facebook Instant Articles SDK for PHP](https://github.com/facebook/facebook-instant-articles-sdk-php) which contains a Transformer that does all the heavy lifting of converting general markup into valid Instant Articles markup.)

We've extended our documentation with a section dedicated to giving clarity on how [Transformer Rules work and how to configure them](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#transformer-rules), along with supporting examples.

**Comment by demoive** [comment] 2016-05-06 11:39
Let's close out this issue for now since all the items have been dealt with.

**Closed** 2016-05-06 12:19 UTC
