### ISSUE TITLE
No rules defined for <div> in the context of InstantArticle

### ISSUE THREAD

**Issue by gentios** [Automattic/facebook-instant-articles-wp#787] opened 2017-10-20 09:22 UTC
# Steps required to reproduce the problem
I am trying to convert this to an instant article, how to do this 

>  This post will not be submitted to Instant Articles because it is missing content.
>  This post was transformed into an Instant Article with some warnings [Learn more | Transformer rule configuration | Toggle debug information]
> 
> No rules defined for `<div>` in the context of InstantArticle

1. Write Article
2. Submit it 

# Expected Result

* Article to be converted

# Actual Result

* Article is not converted

---

**Version Info**

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by timjacobi** [comment] 2017-10-26 21:23
Duplicate of #582

**Closed by timjacobi** 2017-10-26 21:23 UTC
