### ISSUE TITLE
<div class="embed"> wrapping embeds on non-instant articles. 

### ISSUE THREAD

**Issue by kitwestneat** [Automattic/facebook-instant-articles-wp#249] opened 2016-05-10 19:54 UTC
It appears as if embeds.php strips out all embed filters from other plugins, and adds its own filters, one of which wraps the embed in a &lt;div class="embed"&gt; tag. The problem is that it looks as if embeds.php is run regardless of whether or not the request is for an instant feed.

**Comment by dashaluna** [comment] 2016-11-23 12:26
What's the status with this?

**Comment by timjacobi** [comment] 2017-10-03 13:04
Marking this as duplicate of #337 which has more details.

**Closed by timjacobi** 2017-10-03 13:04 UTC
Labels: bug, Transformation
