### ISSUE TITLE
Invalid Scopes message upon connection

### ISSUE THREAD

**Issue by sgatz** [Automattic/facebook-instant-articles-wp#102] opened 2016-04-12 04:25 UTC
When I go to login via facebook, I get this error in a popup:

Invalid Scopes: pages_manage_instant_articles, pages_show_list. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by diegoquinteiro** [comment] 2016-04-12 14:47
Hi @sgatz,

Thanks for the feedback!

Is this still happening?

I couldn't reproduce.

**Comment by diegoquinteiro** [comment] 2016-04-13 16:58
Hi @sgatz,

This was fixed in v2.6

Please reopen if you still have issues.

**Closed by diegoquinteiro** 2016-04-13 16:58 UTC

**Comment by sgatz** [comment] 2016-04-14 01:17
@diegoquinteiro it works perfectly on both our sites.  Thanks for all your super-fast work over the last few days!

**Comment by vvsmanoharvadapalli** [comment] 2018-06-18 06:19
I'm using v3.0 and I am getting the same issue.

**Comment by said-java** [comment] 2018-07-14 23:32
I'm using v3.0 and I am getting the same issue.
Invalid Scopes: manage_pages, publish_pages. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by everton-rosario** [comment] 2018-07-18 13:35
Hey @vvsmanoharvadapalli and @said-java Can you give more details about the problem you're facing?

I want to understand where you are using the login with FB on the plugin.

**Comment by said-java** [comment] 2018-07-18 17:21
@everton-rosario

i want to post in my profile i have ,

Facebook - ERROR -  Graph returned an error: (#200) Requires either publish_actions permission, or manage_pages and publish_pages as an admin with sufficient administrative permission
