### ISSUE TITLE
Cannot Activate

### ISSUE THREAD

**Issue by hatoolah** [Automattic/facebook-instant-articles-wp#430] opened 2016-08-31 21:48 UTC
# Steps required to reproduce the problem
1. Download instant articles wp from plugins directory in WordPress (administrator)
2. Activate plugin
# Expected Result
1. Plugin activated
# Actual Result
1. Dialogue Box: "Plugin could not be activated because it triggered a fatal error." and "Parse error: syntax error, unexpected T_FUNCTION in /home/estuaryu/public_html/wp/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 18"

---

*\* Version Info **
- Plugin version: 3.1.1
- WordPress version: 4.6
- PHP version: 5.2.17

**Comment by diegoquinteiro** [comment] 2016-12-22 05:41
That should be fixed in 3.2+, please update and re-open this issue if that still happens. 

Thank you,
Diego

**Closed by diegoquinteiro** 2016-12-22 05:41 UTC

**Comment by neliocastro** [comment] 2017-10-19 12:13
Still have the same problem. My version is: 4.0.5

Parse error: syntax error, unexpected '[' in /home/bca/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 107

**Comment by everton-rosario** [comment] 2017-10-19 16:34
@neliocastro What is your php version?

**Comment by Sazarimma** [comment] 2019-08-09 00:40
Hello there,

I have a problem and if possible please help me. Currently, my FBIA works fine and the issue is I want to exclude some of the post to be posted as IA. And now I just download this plugin and I will install it later, I want to know, do I have to delete FBIA plugin from WP directory first and install this plugin from Github afterwards? Please guide me. Thank you.
