### ISSUE TITLE
The Wordpress plugin is not working at all.

### ISSUE THREAD

**Issue by DaYWhiTe** [Automattic/facebook-instant-articles-wp#657] opened 2017-03-29 18:03 UTC
# Steps required to reproduce the problem

1. The rss feed is missing.
2. Articles, videos and pictures do not appear.
3. I'm trying to fix it in 2-3 weeks.

# Expected Result

* 

# Actual Result

* 
Instant Article feed link;
http://quikegaming.com/feed/instant-articles

![17634168_500027553454553_5861913443098951680_n](https://cloud.githubusercontent.com/assets/21060067/24469080/09722026-14c3-11e7-9b84-c159a6de6732.jpg)
![17527939_764583527032335_7405339649205338112_n](https://cloud.githubusercontent.com/assets/21060067/24469083/09a45122-14c3-11e7-951b-6f87c1eed488.jpg)
![17639112_293493904406925_5456041683621773312_n](https://cloud.githubusercontent.com/assets/21060067/24469084/09a60f94-14c3-11e7-95a2-edf91cda2fe0.jpg)
![adsiz](https://cloud.githubusercontent.com/assets/21060067/24469081/09a01d3c-14c3-11e7-8433-e7689c160135.png)
![adsiz2](https://cloud.githubusercontent.com/assets/21060067/24469082/09a42274-14c3-11e7-8b6d-853ef48df182.png)
---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.3
* PHP version: 7.0

**Comment by JamesVeeAng** [comment] 2017-04-18 06:03
facing this problem too,are you fixed?

**Comment by timjacobi** [comment] 2017-10-04 16:34
Can you please update to the latest version and report if this is still an issue. If so please post your HTML mark-up.

**Comment by Sukhwinder500** [comment] 2017-10-24 07:14
Hi i also facing this type of error please help me for this...
www.onlinetvstar.com

![rejected](https://user-images.githubusercontent.com/32815650/31929286-12b97004-b8b9-11e7-89cb-50413cda38b2.jpg)

**Comment by timjacobi** [comment] 2017-10-25 15:23
Again, please post your HTML mark-up.

**Comment by Sukhwinder500** [comment] 2017-10-26 05:06
@timjacobi wordpress version 4.4.6 actually the problem is m using plugin for embed videos from youtube. any solution. how to use third party player in fb instant article

**Comment by Sukhwinder500** [comment] 2017-10-28 07:26
@timjacobi reply plz

**Comment by timjacobi** [comment] 2017-10-30 12:21
You can always write your own rules to support 3rd party plugins.

**Comment by Sukhwinder500** [comment] 2017-10-31 06:28
@timjacobi any example... please m using Viduze Wordpress theme

**Comment by timjacobi** [comment] 2017-10-31 12:12
Please refer this [this](https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules) document.

Closing as the original author hasn't responded in too long.

**Closed by timjacobi** 2017-10-31 12:12 UTC
