### ISSUE TITLE
No rules defined for <div class="td-paragraph-padding-4"> in the context of InstantArticle

### ISSUE THREAD

**Issue by wwms9967** [Automattic/facebook-instant-articles-wp#764] opened 2017-09-14 08:04 UTC
I have submitted my articles to facebook for review, and it appears that I have a problem with the paragraphs. 
I don't know how to create a rule so that I can solve all the paragraphs issues all over the website, please help.
Thx.

**Comment by timjacobi** [comment] 2017-10-02 16:04
Could you please add some examples so we can debug this?

**Comment by timjacobi** [comment] 2017-10-03 15:18
Duplicate of #582

Please continue the discussion there.

**Closed by timjacobi** 2017-10-03 15:18 UTC
Labels: more info needed
