### ISSUE TITLE
'Submit for Review' causes permissions error

### ISSUE THREAD

**Issue by peterdalydickson** [Automattic/facebook-instant-articles-wp#470] opened 2016-09-19 19:42 UTC
# Steps required to reproduce the problem
1. Connect app and page
2. Click 'Submit for Review' 
# Expected Result
- articles submitted for review
# Actual Result
- 
  <img width="1294" alt="instant_articles_setup_wizard_ _sephora_promo_code_club_ _wordpress" src="https://cloud.githubusercontent.com/assets/17453188/18646449/7661020c-7ea9-11e6-935f-62f2319e29f2.png">

---

*\* Version Info **
- Plugin version: 3.1.3
- WordPress version: 4.6.1
- PHP version: 5.5.9

**Comment by ajinkya** [comment] 2016-10-02 22:58
Exact Same Issue here...

**Comment by Chakalol** [comment] 2016-10-06 13:31
Same issue in here, anyone found a solution please ? That's crazy... :/

**Comment by euaan** [comment] 2016-10-07 12:30
Same problem here.

**Comment by everton-rosario** [comment] 2016-10-07 15:28
@peterdalydickson @ajinkya @Chakalol @euaan Thanks for reporting this.
Any of you guys have more details?

Check if this workaround works for any of you guys:

- Make sure you can access "All Settings" page for your WordPress installation
- Make sure you have the latest plugin version (currently v3.1.3)
- Navigate to `/wp-admin/options.php` of your installation
- Clear out the value of the option named `instant-articles-current-state`
- Click the "Save Changes" button at the bottom

This will force the plugin to revert to it’s initial state for the Setup Wizard and you can input a new App ID and App Secret.

**Comment by janiosarmento** [comment] 2016-10-07 16:14
This workaround doesn't work.

I cleared all the `instant-articles-%` settings, and was able to run the wizard from beginning, but after all I got the same error with new App Id/App Secret pair.

Perhaps the instructions are not clear enough about what users should do. It's not possible that so many people can't understand what they are supposed to do in order to set this plugin up.

**Comment by everton-rosario** [comment] 2016-10-07 17:39
@janiosarmento Do you have more info or any log on your server?
Any connection between the plugin and the API services with authentication problem will raise this message. Please share with us the details on your logs so we can help improve the plugin showing proper error message and also providing help to your case scenario.

**Comment by janiosarmento** [comment] 2016-10-07 20:14
Unfortunately there is nothing in regular logs. Do you think it would be useful to enable WP_DEBUG, or something?

My blog works under HTTPS, and the instructions tell to provide HTTP URL in Facebook App settings. Is there something here?

**Comment by dcfairwi** [comment] 2016-10-12 01:31
Getting 'Permissions Error' on the very last step when pressing 'Submit for Review' button on the plugin.  Any help is appreciated!

**Comment by sous-studio** [comment] 2016-10-14 06:27
+1 same error

**Comment by john-yw** [comment] 2016-10-14 07:59
+1, thought new update would solve this but no cigar.

**Comment by peterdalydickson** [comment] 2016-10-16 15:48
@everton-rosario I reset as you suggested and experienced the same as @janiosarmento i.e. I still get 'Permissions error' as per my original post.

I'm now on version 3.2 of the plugin.

**Comment by peterdalydickson** [comment] 2016-10-16 17:15
@everton-rosario which logs should I review?

**Comment by peterdalydickson** [comment] 2016-10-17 08:52
@janiosarmento I turned off SSL on my site and still got the permissions error. Have you managed to track anything down?

**Comment by peterdalydickson** [comment] 2016-10-17 09:05
@janiosarmento When I turned SSL back on and clicked to submit articles again, it worked. Would you confirm if that's the case for you too? Is there something in this @everton-rosario ?

**Comment by sous-studio** [comment] 2016-10-17 09:10
@peterdalydickson I had the same problem. I just submitted it through Facebook, without plugin. Now plugin shows it's been reviewed.

**Comment by john-yw** [comment] 2016-10-17 09:48
@sous-studio how did you do that? Is the plugin now working for you?

**Comment by sous-studio** [comment] 2016-10-17 09:58
@john-yw as I said, I just sent articles to review from Facebook instead of plugin. And plugin fetched that it's being reviewed.

**Comment by john-yw** [comment] 2016-10-17 10:01
nice.

**Comment by sous-studio** [comment] 2016-10-17 10:04
A bit off-topic folks, but I was wondering - why this review process? Anyone with experience of it? Do they like look for content to be properly formatted, or check it against editorial policy of Facebook?

**Comment by philipjohn** [comment] 2016-10-23 18:32
Just got this myself folks.

@everton-rosario Those steps above didn't work for me either. Of note, trying to delete the value of the `instant-articles-current-state` to remove `STATE_REVIEW_SUBMISSION` didn't do anything - the value remained. Other values I tried were `false`, `null` and `0` - none of which stuck - it always restored to `STATE_REVIEW_SUBMISSION` and the wizard remained in the same state.

I also went to my Facebook page and navigated to Publishing Tools > Instant Articles > Configuration. Under "Step 2: Submit For Review" I'm told there are "not enough articles".

The "Production Articles" section shows four articles. I re-saved another post to make it five, and tried the "Submit for Review" button in the wizard again. No dice.

Hitting "Submit for Review" on Facebook instead, as @sous-studio did worked fine and the wizard in WP now shoes I'm awaiting review.

Feel free to dig deeper into my setup on  your end if it helps. You know my FB profile already, the site is lichfieldlive.co.uk and the page is [here](https://www.facebook.com/Lichfield-Live-204842129559071/).

**Comment by everton-rosario** [comment] 2016-10-28 13:06
@philipjohn @sous-studio @john-yw @peterdalydickson @dcfairwi @janiosarmento 
I've noticed few others struggling to get thru the finish line since the plugin isn't properly validating the APP id/APP secret correctly, thus the backend response is `Authentication Error` since it failed to properly complete request with invalid APP ID/ Secret.

Just to make sure that this isn't the issue you might have, please consider setting the app ID and secret again following these steps:

1. Click on the `edit` pencil on the right of your APP ID
2. Enter your APP ID 
3. From your Application, certify you are clicking on the button `Show Secret` then copy it from there
4. Hit next
5. Login with Facebook to update the authorization token
6. Select the correct Page (The page you are selecting should have **exactly** same URL from your Application and the URL you claimed --  this also leads to errors on the process)
7. Click to edit the style (just to make the next button appear) 
8. If not yet submitted for review, make sure you have at least 5 articles and hit to submit for review (make sure your articles have no transformation warnings)
9. You should be good to go.

PS:
If you sit on step 6 for some hours, maybe days, the token might have expired and then you might need to restart from beginning
**Really** pay attention to the transformation warnings and make sure you've fixed them all. On this new version 3.2, we are blocking on the plugin, submission of articles with warnings, since they might have content missing/misstransformed.

Hope this fits your case.

**Comment by naroga** [comment] 2016-11-09 13:49
+1

**Comment by pascalbajorat** [comment] 2016-11-10 23:51
@everton-rosario I've done all those steps and receive also this error message: "Permissions error"

**Comment by Rexdomine** [comment] 2016-11-17 11:43
still having that permission error issue

**Comment by ndiro** [comment] 2016-11-26 10:58
+1

**Comment by yameenr** [comment] 2016-12-01 11:12
Same here.

**Comment by anujchhabria** [comment] 2016-12-14 05:12
I followed all the steps but I’m still facing the permissions error issue!

**Comment by MervinPraison** [comment] 2016-12-14 11:10
Please go to developers.facebook.com

1. Go to My Apps. 
2. Click "App Review"
3. Select the option "Make my [APP] public" as YES

That would do the trick. 

Thanks

**Comment by anujchhabria** [comment] 2016-12-15 14:18
Hi, Tried these steps but still getting the same error!

**Comment by andrefrcastro** [comment] 2016-12-27 12:38
It may be related with some pages being managed with business.facebook.com/page_id instead of facebook.com/page_id

**Comment by everton-rosario** [comment] 2016-12-27 13:42
@anujchhabria , Does your case seems like @andrefrcastro ?
Any of you guys have more details?
Feel free to send, so I can try to debug any other internal tool @ Facebook.

**Comment by ndiro** [comment] 2016-12-27 14:55
Removing from Business Facebook⁣ solved for me. ​

Il giorno 27 Dic 2016 14:42, alle ore 14:42, Everton Rosario <notifications@github.com> ha scritto:

**Comment by everton-rosario** [comment] 2016-12-27 15:06
Can you explain how more people facing this can proceed to remove from business as well, @ndiro ?
Thanks for your support!

**Comment by ndiro** [comment] 2016-12-27 15:12
Sure, It is a simple process well explained here:

https://www.facebook.com/business/help/816230598469434⁣

​

Il giorno 27 Dic 2016 16:06, alle ore 16:06, Everton Rosario <notifications@github.com> ha scritto:

**Comment by lekhakmukesh** [comment] 2016-12-30 15:00
I am getting the same error. 

Here is the error message :- 

Warning: DOMDocument::loadHTML(): Empty string supplied as input in /home/lekhakmukesh/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php on line 178

**Comment by varyagina** [comment] 2017-01-08 02:31
I have the same issue. I have tried all the suggestions from the above and nothing works. :((

**Comment by rwkyyy** [comment] 2017-01-18 12:42
Same error, solved by using @everton-rosario solution combined with @sous-studio .

More exactly I reset the plugin ti'll that point, after that it showed in facebook I got articles and I can submit them for review and I used that, now waiting for approval.

Wierd thing is that this is my 2nd install and I had no issues with the 1st one (on this part).

**Comment by jeremyclarke** [comment] 2017-02-07 17:29
Having this problem with 4.7.2 and latest plugin. 
Tried resetting everything in the plugin: same outcome. 

Resolved my need by going though my facebook page and getting to publishing tools>instant articles and submitting from there. 

Nasty bug though. 

IMHO if devs don't have a solution for this because it's random, please add a link or instructions to get to the FB page where we can submit. It exists and is waiting, but is very hard to find when you expect the plugin to be working.

**Comment by wellbeinb** [comment] 2017-02-17 09:40
This is just so weird. Upon clicking the 'Submit for Review' button, it showed me the 'Permissions error'. But upon checking on the Facebook page, under Production Articles, 11 of my blog posts with the status 'Unpublished'. Does it mean that id did went through to Facebook for review? If so, I'll just need to wait a couple more days and wait if the articles were published. 

_Please see attached file for reference..._

![image](https://cloud.githubusercontent.com/assets/11327086/23060278/0f9a1418-f538-11e6-8d0b-13f79306577a.png)

**Comment by wellbeinb** [comment] 2017-02-17 09:41
Can someone explain what's shown on the photo above I'm confused now... Thanks in advance...

**Comment by wellbeinb** [comment] 2017-02-17 09:42
Just a follow-up on the above photo, here's the screenshot on the error part:

![image](https://cloud.githubusercontent.com/assets/11327086/23060394/7f4494be-f538-11e6-8091-13a9e257c14b.png)

**Comment by jeremyclarke** [comment] 2017-02-17 14:23
@wellbeinb That screenshot shows a lot of items marked as from RSS. You should review your settings as RSS isn't how this plugin works. The posts that aren't RSS are probably the ones from the plugin, and the ones you should submit for review. 

I can confirm that when a page has submitted for review but not been accepted, the posts in that list are marked as "Unpublished" despite being published inside WP. Once the page is accepted after review, they will show "Live".

**Comment by iamasalesman** [comment] 2017-02-18 11:48
Just found solution to this issue. Plugin having bugs . Can't submit from wo admin. Instead update last 5 posts. Use submit for review on face  book page setting instant article tab. It will work fine. Then refresh wordpress and you will see it's submitted. Enjoy !

**Comment by gumruyanzh** [comment] 2017-03-21 13:27
I had a problem like this, and solved it by adding a LOGO at facebook site, unther **publish tools->instant artcles->configure**
After that, plugin works perfect

**Comment by digitpedia** [comment] 2017-03-21 17:04
I did same as guys above. Use the facebook 'Instant Articles Configuration' section to try and fix it rather than the wordpress plugin. I had a problem with the logo and with it only picking up 4 articles, managed to fix both issues by using facebook instead of the plugin.

**Comment by chercka** [comment] 2017-04-13 19:18
Same fix as others - added a logo and re-saved some blog posts to make them show up as new. Worked submitting it from the WP plugin.

**Comment by fterradev** [comment] 2017-04-18 15:41
I had tried it before 2 weeks ago and it didn't work. Now it did and I finally managed to insert the logo on our page's style though Styles Editor. But I think setting the logo is not the responsible for it. It's still unknown for me.

I just want to point out that at first my submission raised "Permission error" but as I can recall it did without even showing the loading animation for some seconds which I see now! (I still got the "Permission error" message after that)

Moreover, the Settings section at Publish Tools > Instant Articles did not point out the "Absent Logo" issue which it does now. (maybe that's not the exact message you see since I'm translating what I see in Brazilian Portuguese to English. The same applies to further messages and labels)

This issue shows up inside a "Resolve these issues before submitting" panel (still under Publish Tools > Instant Articles > Settings). As it explains, this must be done on our page's style via Styles Editor.

Anyway as I said I think the main thing regarding this bug is not about the logo. I think when the "absent logo" issue is raised on Instant Articles Settings, it means the plugin managed to send the articles - though it still shows the Permission Error... When submitting, after the loading animation and the Permission Error, you can also check if some articles (I suppose from 10 to 20) appears under Production Articles section.

**Comment by baderrami** [comment] 2017-04-19 08:28
don't submit your articles from wordpress, open your fb page > publishing tools > config. > submit articles for review. that's it, If you go back to your WP panel nad refresh the page you'll see that the articles are submitted.

**Comment by humet** [comment] 2017-05-04 13:18
Here's what I did to get it working:

1) Follow setup wizard in Instant Articles plugin
2) Make sure you add a logo to the style and don't create a new style, overwrite the default
3) Submit articles for review in the plugin, you'll get the permissions error
4) Go to FB page > Publishing Tools > Production Articles. You should see 5 of your posts here.
5) Go to Configuration. If there's no errors you will be able to submit for review. If there are errors, fix them, delete the posts in Production Articles and go back to step 3.
6) When submitted, the plugin updates in Wordpress

**Comment by off-bank** [comment] 2017-05-13 20:05
Going to My Apps -> settings and adding app domain fixed the permission issue.

**Comment by raespresso** [comment] 2017-05-16 19:14
Ok, I tried EVERY suggestion here. The ONLY thing that worked was combining two ideas:
-Click "Publish" one more time on each of the five most recent posts in WP
-When you're in Facebook Page > Publishing Tools > Instant Articles > Configuration, you'll want to click "Submit for review" under Step 2 and submit them from FB instead of within WP.

**Comment by nonsintetic** [comment] 2017-05-18 10:26
**I managed to fix it on my end!** Following the advice above I went to Posts in WP and re-saved the last 5 articles. When you save one you can also see if it was submitted to Facebook (in wordpress on the edit page there's a meta-box under the content editor for this). When I had 5 articles saved and submitted I just went to Facebook's instant articles settings page (the Publishing Tools tab when you view your page) and clicked submit. It worked!

In light of this maybe change the Permissions Error to something more clear like 'Check if you have 5 articles submitted). 

No need to do the RSS thing, that just pretty much bypasses most of the plugin.

**Comment by timjacobi** [comment] 2017-10-02 12:52
Can you please update to the latest version of the plugin and report if this problem still exists?

**Comment by mburak** [comment] 2018-01-19 16:30
Couldn't reproduce this with the latest version, please feel free to re-open if you still experiencing this problem.

**Closed by mburak** 2018-01-19 16:30 UTC
