### ISSUE TITLE
Heading inside blockquotes not present in rss feed

### ISSUE THREAD

**Issue by nikssardana** [Automattic/facebook-instant-articles-wp#262] opened 2016-05-13 14:58 UTC
I installed this plugin on my blog http://www.sugeek.net. However, when the instant articles were submitted for review, they were rejected, reason being "Missing content - text elements". The text inside < blockquote >< h1 > ... < /h1 >< /blockquote > tags was not present in the rss feed generated by the plugin. (http://www.sugeek.net/feed/instant-articles). Rather, it shows an empty < blockquote > < /blockquote > tag set. Is there some workaround? Here is a  screenshots of the rss feed:

![problem](https://cloud.githubusercontent.com/assets/14257973/15251825/d890d360-1948-11e6-8eaf-e98eccf292ab.png)

And the actual post text as seen in wordpress editor:

![problemactualthing](https://cloud.githubusercontent.com/assets/14257973/15251828/d8fcc7dc-1948-11e6-9d90-9495ff6481c8.png)

Similar thing happened with other posts as well.

**Comment by jeremyclarke** [comment] 2016-10-25 19:16
Anyone else?

From what I can tell you have dreamed too big with your blockquote > h1. Not only is what you're experiencing the expected behavior, AFAIK there is no way to get the result you would hope for!

What you need to do is a "Transformation" for the selector "blockquote h1". The problem is that the special "rules" for headings, H2Rule and H1Rule can ONLY work in the context of the document root, so even if you try to set up a transformation of "blockquote h1 > H2Rule" it won't work, it will silently fail. 

You can do a much dumber transformation of "blockquote h1 > BoldRule" but that will probably not be what you want, since it will be an inline strong tag with no line break between it and whatever comes next in the blockquote.

**Comment by mburak** [comment] 2018-01-19 17:28
Hi @nikssardana, it's being a while since you posted this issue. Does this still happen to you? Did you try with the latest version of the plugin?
Thanks!

**Comment by jerclarke** [comment] 2018-01-19 17:40
@mburak Did you read my answer? This is expected behavior with no possible solution outside Facebook changing the API. If you want to close this ticket then go ahead and do so. 

Modern versions of the iA plugin will have the following outcome: The post is marked as invalid for iA and never submitted to Facebook. That is the correct behavior because Instant Articles can't show a heading inside a blockquote, and any transformation that would work (e.g. making it bold) will be confusing to users because the bold text wont' behave like a heading.

I propose the outcome of this ticket is "Facebook refuses to support `blockquote > h1` and any post with that formatting is doomed to never be iA unless it's content is altered".

**Comment by diegoquinteiro** [comment] 2018-04-13 18:41
Hi @jerclarke. Thanks for your feedback. As you correctly stated this is not an issue with the plugin, and for any feature not supported by Instant Articles itself the intended behavior is to fallback to the m-web version, so I will close this issue.

Instant Articles is not a browser engine, it renders natively all its supported components and does it over a large subset of HTML5, but not for the complete set of HTML5 tags and tag combinations. We are constantly improving the Instant Article format to meet the demands of the real-life scenarios, so we appreciate your feedback on this particular use case.

**Closed by diegoquinteiro** 2018-04-13 18:41 UTC
Labels: help wanted, more info needed, transformation
