### ISSUE TITLE
Instant Article does not have any content

### ISSUE THREAD

**Issue by jclanoe** [Automattic/facebook-instant-articles-wp#131] opened 2016-04-13 17:22 UTC
It appears that Facebook successfully imported the IA using the RSS feed, but they're showing an error message on every imported item.

> **General Errors: Empty Instant Article: The Instant Article does not have any content.**

![image](https://cloud.githubusercontent.com/assets/1064971/14502629/82683324-01ac-11e6-9031-bcb0516f6027.png)

Here's the general view in the Page settings:

![image](https://cloud.githubusercontent.com/assets/1064971/14502690/d507632a-01ac-11e6-9e34-f8d53e43d2d3.png)

And the RSS feed URL is https://clemaroundthecorner.com/feed/instant-articles.

**Comment by ireade** [comment] 2016-04-14 08:22
I'm also having the same issue

![screen shot 2016-04-14 at 09 21 16](https://cloud.githubusercontent.com/assets/8677283/14521661/4c003d56-0222-11e6-9192-d98a943ce33a.png)

**Comment by ludsonaiello** [comment] 2016-04-14 15:04
I've the same problem.

**Comment by diegoquinteiro** [comment] 2016-04-14 18:08
Hi, guys. Thanks for the feedback.

Could you provide some more information about the issue you're having? That will help us reproduce the issue.

- What version of the plugin are you using?
- What version of WordPress are you using?
- What version of PHP are you using (if known)?
- What's the debug output shown in the post edit screen on the Facebook Instant Article box (both sides)?

Thanks again!

**Comment by ludsonaiello** [comment] 2016-04-14 18:37
Hi @diegoquinteiro. Tks for your support.

I'm using the last version of the plugin. I updated today for the last release.
My wordpress is the last version too, is 4.5
I'm using PHP 5.5.3 and the output show me same as images of this topic, the IA run only the header (including images, logo, title), but they don't get the post content. Show the information: Body Empty.

**Comment by ireade** [comment] 2016-04-14 19:15
Hi @diegoquinteiro ! In answer to your questions.

1. Version 2.7 of the plugin, just did an update today
2. Wordpress version 4.5
3. PHP version 5.5.9
4. "General Errors: Empty Instant Article: The Instant Article does not have any content." . See the image from above.

Hope that helped

**Comment by YOzaz** [comment] 2016-04-15 08:22
Hi, same issue here.

**Comment by jclanoe** [comment] 2016-04-15 09:50
@diegoquinteiro 

1. Plugin 2.5
2. Wordpress 4.5
3. PHP 5.5.9
4. `General Errors: Empty Instant Article: The Instant Article does not have any content.`

Thanks!

**Comment by equa2k9** [comment] 2016-04-20 13:58
That helps me, I use PageBuilder by SiteOrigin
```
{
        "rules" :
            [
                {
                    "class": "PassThroughRule",
                    "selector" : "div"
                },
{
                "class": "TextNodeRule"
            },
{
                "class": "PassThroughRule",
                "selector" : "html"
            },
            
            {
                "class": "PassThroughRule",
                "selector" : "script"
            },
            {
                "class": "PassThroughRule",
                "selector" : "body"
            },
            {
                "class": "ItalicRule",
                "selector" : "i"
            },
            {
                "class": "BoldRule",
                "selector" : "b"
            },
            
{
                "class": "ParagraphRule",
                "selector" : "p"
            },

     ]
    }
```

**Comment by perry227** [comment] 2016-04-26 00:28
I'm using WordPress version 4.5 and the PageFrog plugin version 1.0.9, getting exactly the same error as above. I can see the content but it's saying there is no content.

**Comment by CarsonLee27** [comment] 2016-04-29 15:08
Having the same issue =D

**Comment by andyaffleck** [comment] 2016-05-02 16:10
We had this issue. Upgrading to PHP 5.6.x resolved it. Interestingly, ALL different FIA plugins did this exact same thing for us until we upgrade PHP.

**Comment by MattiaConfalonieri** [comment] 2016-05-08 10:04
Same problem here, Quick edit = empty content

PHP 5.6.19 do not resolve problem
Custom transformation rule do not resolve too

**Comment by jeremyongws** [comment] 2016-05-14 13:03
Having the same issue, running on PHP 7 and the latest version of WP and the plugin.

Error is : "General Errors: Empty Articles: You have one or more articles without any content."

**Comment by demoive** [comment] 2016-05-20 10:35
There have been similar reports of issues with unexpected empty content which were fixed in versions v2.8 and v2.11 of the plugin. If you're still experiencing the issue, could you update to the latest versions and reopen if it still reproduces?

Occasionally, simply updating the plugin wasn't enough for the problem to go away, but articles had to be re-saved/re-published* — this was because the articles were submitted with empty content because of their status/published state (scheduled, draft, etc.).

*Fortunately, a fix in v2.9 (#160 #180) also allowed for the ability to publish articles in bulk :-)

**Comment by MattiaConfalonieri** [comment] 2016-05-20 10:38
I confirm that the last update resolve the problem...

**Comment by markbarnes** [comment] 2016-05-20 10:42
_**I composed the post below before @demoive posted above. As it took me a while to type, I'm leaving it here whilst I test 2.11. I'll report back later.**_

I have the same issue. According to Facebook, my production feed doesn't have any content. What's interesting is (a) when I view the feed it looks fine; (b) Facebook says the development feed is fine, even though the feed URL is identical!; (c) some filters I have added to the feed (e.g. author) aren't reflected in the production feed.

The screenshots below show two images, one from the production feed and one from the development feed - again, both with identical URLs!

![fia](https://cloud.githubusercontent.com/assets/128895/15425271/1b58b376-1e7f-11e6-8fbb-5af54780af55.png)

![fia2](https://cloud.githubusercontent.com/assets/128895/15425339/8ebaa5b8-1e7f-11e6-87d0-e6b27160cbb6.png)

**Comment by jclanoe** [comment] 2016-05-20 10:54
I installed 2.11 and there's still no content in that feed. Note that I manually updated a few posts before testing it.

**Closed** 2016-05-20 12:24 UTC

**Comment by echenze** [comment] 2016-06-12 15:21
I'm having the same problem as the others have reported here. Any fix?

**Comment by whitesiroi** [comment] 2016-06-15 09:46
The same here "Empty Articles: You have one or more articles without any content.".
Using Instant Articles API in Graph API Explorer

Here is the content I'm testing on:
```
<head>
  <meta charset="utf-8">
  <meta property="op:markup_version" content="v1.0">

  <!-- The URL of the web version of your article --> 
  <link rel="canonical" href="http://mydomain/article">
  
  <!-- The style to be used for this article --> 
  <meta property="fb:article_style" content="default">
</head>
<body>
  <article>
    <header>
      <!-- The cover image shown inside your article --> 
      <figure>
        <img src="http://mydomain.com/the_image.jpg" />
        <figcaption>This image is amazing</figcaption>
      </figure>
      
      <!-- The title and subtitle shown in your article -->
      <h1> Title </h1>
      <h2> Subtitle </h2>

      <!-- A kicker for your article -->
      <h3 class="op-kicker">
        This is a kicker
      </h3>

      <!-- The author of your article -->
      <address>
        <a rel="facebook" href="http://facebook.com/somedude">The somedude</a>
        somedude is a avid zombie hunter.
      </address>

      <!-- The published and last modified time stamps -->
      <time class="op-published" dateTime="2015-11-11T04:44:16Z">December 11th, 4:44 PM</time>
      <time class="op-modified" dateTime="2015-11-11T04:44:16Z">December 11th, 4:44 PM</time>
    </header>
  </article>
</body>
```

**Comment by equa2k9** [comment] 2016-06-15 15:38
if you are using some pagebuilder, i use SiteOrigin pagebuilder
this in file 

> facebook-instant-article.php

just comment  
`//	add_filter( 'posts_where' , 'instant_articles_query_where', 10, 2 );`

for me it solves the problem with no content in instant article, because this pagebuilder save all content in post meta and not in post_content

**Comment by whitesiroi** [comment] 2016-06-17 05:51
Sorry, In my case I didn't have anything after <time ...>...</time> tags so thats why I got that message 

> General Errors: Empty Articles: You have one or more articles without any content.

After<time> tag adding any stuff like for example <p>A</p> I stopped getting the error message.

Just in case full html for example:
`<head>
  <meta charset="utf-8">
  <meta property="op:markup_version" content="v1.0">

   
  <link rel="canonical" href="http://mydomain/article">

   
  <meta property="fb:article_style" content="default">
</head>
<body>
  <article>
    <header>
       
      <figure>
        <img src="http://mydomain.com/the_image.jpg" />
        <figcaption>This image is amazing</figcaption>
      </figure>

      
      <h1> Title </h1>
      <h2> Subtitle </h2>

      
      <h3 class="op-kicker">
        This is a kicker
      </h3>

      
      <address>
        <a rel="facebook" href="http://facebook.com/somedude">The somedude</a>
        somedude is a avid zombie hunter.
      </address>

      
      <time class="op-published" dateTime="2015-11-11T04:44:16Z">December 11th, 4:44 PM</time>
      <time class="op-modified" dateTime="2015-11-11T04:44:16Z">December 11th, 4:44 PM</time>
<p>A</p>
    </header>
  </article>
</body>`

**Comment by hengsoheak** [comment] 2016-12-29 16:20
Really confusing and difficulties for developer why FB make something easier like google?

**Comment by Moosabeqreth** [comment] 2017-07-22 07:49
Getting same error aswell! 
Plugin: 4.0
Wordpress: 4.8
PHP: 5.4

Error: This post will not be submitted to Instant Articles because it is missing content.
No rules defined for <div> in the context of InstantArticle

Pasting Code: 
<div id="dslc-theme-content"><div id="dslc-theme-content-inner"> <p><img class="aligncenter wp-image-176" title="Bridal Lehenga" src="http://www.kashishindia.com/wp-content/uploads/2017/07/Kashish-Post-design-300x188.jpg" alt="" width="687" height="430" srcset="http://www.kashishindia.com/wp-content/uploads/2017/07/Kashish-Post-design-300x188.jpg 300w, http://www.kashishindia.com/wp-content/uploads/2017/07/Kashish-Post-design-768x482.jpg 768w, http://www.kashishindia.com/wp-content/uploads/2017/07/Kashish-Post-design-1024x643.jpg 1024w" sizes="(max-width: 687px) 100vw, 687px"></p> <p style="text-align: center;"><strong>How to selected perfect Lehenga which fits best  for your Wedding Day!</strong></p> <p style="text-align: center;">Hello Dear Bride-To-Be,<br> Your special day is just about to arrive  and are you still worrying about the perfect lehenga for Your Wedding Day? Haven’t really been able to decide amongst the Tons of options that have been advised to you? So, if you are browsing online for tips to choose a lehenga then you have reached to the right place! Be ready to be amazed with some great tips, on your terms! So, shut out all the babble. Keep calm and scroll through these top tips to select the perfect Bridal lehenga for your wedding.</p> <p style="text-align: center;"><strong>Recognise your body type</strong><br> When a specific style maybe in fashion, it may not exactly be your style. There are ton of styles that will make you look just as Amazing, Highlighting  your curves and increasing your looks. So, it is all about recognising what body type you are and moving on from there.</p> <p style="text-align: center;"><strong> </strong></p> <p style="text-align: center;"><strong>The hourglass</strong><br> The easiest body type to select for, as brides with this body You can drape any lehenga design with perfect ease. Choose bright colours with a pinch of golden zari work for a Stunning look.</p> <p style="text-align: center;"><img class="alignnone wp-image-178" title="Lehenga" src="http://www.kashishindia.com/wp-content/uploads/2017/07/2-233x300.jpg" alt="" width="704" height="906" srcset="http://www.kashishindia.com/wp-content/uploads/2017/07/2-233x300.jpg 233w, http://www.kashishindia.com/wp-content/uploads/2017/07/2-768x988.jpg 768w, http://www.kashishindia.com/wp-content/uploads/2017/07/2-796x1024.jpg 796w" sizes="(max-width: 704px) 100vw, 704px"></p> <p style="text-align: center;"><strong>The skinny Shape</strong></p> <p style="text-align: center;">Select fabrics which add curves to your body. Leave clear of clingy fabrics like chiffons or poly-crepes or satins. Fabrics tussar silk, kosa silks, handloom silks such as Kota and South cottons and heavier weaves like Banarasi and Jamdani are the best  for skinny women. Your midriff is your most valuable asset! So, experiment with your blouse designs and show off that slender frame.</p> <p style="text-align: center;"><strong>The busty bride</strong><br> It’s time you stopped being worried of your assets and select  a lehenga with a blouse design that suits your body. Being stylish is just as important as being comfortable on your special day. So, you don’t necessarily have to wear a low cut blouse to look stylish on your wedding day. Choose a single tone fabric with minimal or no embellishments for your blouse. Play it safe with round or mid-length V necks.</p> <p style="text-align: center;"><strong>The pear-shaped bride</strong><br> Brides with heavier bottom and a curvy waist line, go for flared, panel or A-line lehengas with just a slight flare from the waist. Go for <em>cholis</em> that are embellished with heavy zari and zardosi work as this helps draw attention to the upper half of your body rather than the lower.</p> <p style="text-align: center;"><strong>The athletic bride</strong><br> Contemporary lehengas that are well-fitted from the waist till the knee, and flare out from there are a great pick for the athletic body type as well as women with an hourglass figure.</p> <p style="text-align: center;"><img class="alignnone wp-image-174" title="Wedding Lehenga" src="http://www.kashishindia.com/wp-content/uploads/2017/07/3-300x165.jpg" alt="" width="698" height="384" srcset="http://www.kashishindia.com/wp-content/uploads/2017/07/3-300x165.jpg 300w, http://www.kashishindia.com/wp-content/uploads/2017/07/3-768x423.jpg 768w, http://www.kashishindia.com/wp-content/uploads/2017/07/3-1024x564.jpg 1024w" sizes="(max-width: 698px) 100vw, 698px"></p> <p style="text-align: center;"><strong>The petite bride</strong><br> Struggling to find a lehenga that doesn’t fit your petite frame? Well, don’t worry! Go for a high-waisted lehenga with a thin waist band to create an  illusion of longer legs. selected  a single colour. Also, go for lehengas with vertical patterns to elongate your frame.</p> </div></div>

Kindly Help ASAP!

**Comment by Jordidriesen** [comment] 2017-08-07 16:01
@equa2k9 Is your solution to the instant article feed still working, with siteorigin? Where do I need to put comment and query in the facebook-instant-article.php? Any help is much appreciated, thanks!

**Comment by equa2k9** [comment] 2017-08-07 16:19
@Jordidriesen 
Yeah, with Instant articles version 3.1.3 and siteorigin pagebuilder 2.4.16 It works
http://prntscr.com/g5ho0k

Better way: use in your theme `remove_filter('posts_where' , 'instant_articles_query_where', 10)`
I didn't test it, so try it

**Comment by nawaid38in** [comment] 2017-10-21 03:59
why show 
# General Errors: End tag : expected '>'

**Comment by darinluka** [comment] 2017-12-17 23:06
hi whats up , i have another problem 
General Errors: Unexpected end tag : p ? why give this in all articles thanks

**Comment by BijayaChhetri** [comment] 2018-02-26 05:56
hello i am using  CI framework RSS 
but Why did Facebook stop Importing Instant Articles from our RSS feed?
it was working fine 
https://business.facebook.com/arghakhanchibulletin
http://arghakhanchibulletin.com/rssfeed

Screenshoot:
https://scontent.fktm8-1.fna.fbcdn.net/v/t39.2229-6/27962857_962433253922549_2554686155849203712_n.jpg?oh=e76a127e65147930d709acf2660b3d5a&oe=5B099222

**Comment by javed7744** [comment] 2018-04-09 07:00
General Errors: Empty articles: You have one or more articles without any content
i have the same problem

**Comment by ekendra** [comment] 2020-09-10 08:59
4 years, marked close, but the solution?
