### ISSUE TITLE
How to use the plugin with several funpages and one site?

### ISSUE THREAD

**Issue by Astraport** [Automattic/facebook-instant-articles-wp#820] opened 2017-11-19 17:21 UTC
There's only one field for entering the id of the page. But I have several fanpages that I want to connect to other categories of my site. 
How to do this? TY

**Comment by Astraport** [comment] 2017-11-20 14:13
I will try to do this so, but I doubt that this method will work.

**Comment by everton-rosario** [comment] 2017-11-21 13:21
Also you will need to use the RSS feed as ingestion into each page. Since the default OG ingestion won't be good for you, since it was designed for a single domain <-> FB Page.

You will need to go into each page you use as instant article (that you have claimed the URLs) and set up the URL for RSS feed ingestion.
Generally (if you haven't changed it) the `/instant-articles` path is where the RSS feed is generated. So you'd use this as RSS feed ingestion:  `http://<yourdomain>/instant-articles`

Let me know if this works for you.
Closing out for now.

Join our group @ Facebook if you haven't done so: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.

**Closed by everton-rosario** 2017-11-21 13:21 UTC
Labels: more info needed
