### ISSUE TITLE
I can not activate any page for setting up instant articles, it does not list my pages at all!

### ISSUE THREAD

**Issue by bujaris** [Automattic/facebook-instant-articles-wp#899] opened 2018-03-10 00:14 UTC
## Steps required to reproduce the problem

1. 
2. 
3. 

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 
* WordPress version: 
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by yeah-sir** [comment] 2018-03-15 05:34
Hi @bujaris can you please provide more details on what you are looking to do achieve and the errors you are seeing during the setup?

**Comment by bujaris** [comment] 2018-03-24 21:04
The problem is the following: I have many facebook pages where I am the
admin and when I try to apply for instant article it keep saying me "You
have to be an admin to apply for instant article". Any help for this?


Bujar Ismaili
Student

Faculty of natural sciences and mathematics
<http://www.pmf.ukim.edu.mk/web/pages/news>
"Ss Cyril and Methodius" University in Skopje
Pravda Spasovska, 13
1300 Kumanovo, Republic of Macedonia
tel: 0038977 851 153

**Comment by Honey2580** [comment] 2018-04-06 12:36
The problem is the following: I have many facebook pages where I am the
admin and when I try to apply for instant article it keep saying me "You
have to be an admin to apply for instant article". Any help for this?

**Comment by Honey2580** [comment] 2018-04-06 12:36
Done alot of things by searching on Google did'nt find any useful results kindly help

**Comment by diegoquinteiro** [comment] 2018-04-13 18:46
Hi @Honey2580, this is not an issue with the plugin, so I'll close the issue.

Please refer to this documentation to report a bug on the right channel: https://developers.facebook.com/ia/blog/post/2016/02/02/bug-reporting-tool/

Thank you!

**Closed by diegoquinteiro** 2018-04-13 18:46 UTC
Labels: more info needed
