### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by 7onmoy** [Automattic/facebook-instant-articles-wp#94] opened 2016-04-08 18:26 UTC
After installing the plugin and running composer, everything went smoothly. But when I tried activating the plugin, it gives the following error.

Plugin could not be activated because it triggered a fatal error.
![fatal error](https://cloud.githubusercontent.com/assets/3818333/14393579/5585ea92-fde5-11e5-9c5d-d666177da545.JPG)

No further details.

I've WP_DEBUG, WP_DEBUG_LOG, WP_DEBUG_DISPLAY all on, but still it's blank.
I'm on nginx. Any special rewrite rules required? Where can I check the exact error? Please help.

**Comment by bassbolz** [comment] 2016-04-08 20:49
I'm seeing the same error.  Looks like the code is missing a vendor directory

![image](https://cloud.githubusercontent.com/assets/4229935/14397173/1848a1b6-fd99-11e5-991d-dda46ebe7752.png)

**Comment by trebor3377** [comment] 2016-04-09 02:58
I am also seeing the same error. I checked the plugin folder and it is indeed missing the vendor directory referred to in the PHP error message. A fix for this issue would be appreciated, thanks for your help!

**Comment by 7onmoy** [comment] 2016-04-09 09:25
@bassbolz and @trebor3377 any workaround?

**Comment by willhaynes** [comment] 2016-04-09 21:05
Looks like this was caused by this commit:
https://github.com/Automattic/facebook-instant-articles-wp/commit/8427f3d4106ed3e6fc801e5b7d89db7ee51388e4

**Comment by 7onmoy** [comment] 2016-04-10 10:20
@willhaynes any fixes? How should we proceed?

**Comment by YOzaz** [comment] 2016-04-11 08:41
@willhaynes @7onmoy you need to run `composer install` on plugin directory. It will create `vendor` directory for you.

**Comment by 7onmoy** [comment] 2016-04-11 09:17
@YOzaz I've already done that. My PHP version is 5.5.9

**Comment by YOzaz** [comment] 2016-04-11 09:30
@7onmoy exactly. At the moment, code is built to support PHP 5.6 only - but PR to fix this is on the way: https://github.com/Automattic/facebook-instant-articles-wp/pull/87

**Comment by BranndonWork** [comment] 2016-04-11 13:42
Right, but this is for local copies only... after installing composer, running composer install.... there is a .gitignore file listed that ignores the vendor directory, so pushing this up to our git repository for the project is useless... 

What's the proper way to commit the plugin update if it's ignoring the vendor folder? I can manually allow the vendor folder, but I don't want to screw things up.

**Comment by YOzaz** [comment] 2016-04-11 14:36
@BranndonWork at the moment, plugin is not installable through composer - therefore can't be updated through it. What you're installing using `composer install` is dependencies this plugin requires. They can be updated of course.

**Comment by BranndonWork** [comment] 2016-04-11 14:42
Sorry @YOzaz, I'm new to this. We manage our website updates via our git repository. I code the changes locally, push up to git, then amazon code deploy catches my changes, and pushes them up to our web server. Are you saying that there is no way for me to use this plugin with our setup other than SSHing directly into our amazon EC2 serveR?

**Comment by YOzaz** [comment] 2016-04-11 14:52
@BranndonWork in general yes, for current configuration you need to run `composer install` on production server / environment. However, you can still use old version of plugin, which is installable through general WordPress plugin system, like @donaldG is suggesting:
https://wordpress.org/plugins/fb-instant-articles/

**Comment by stuartshields** [comment] 2016-04-11 22:33
@YOzaz You can't even install the plugin from the WordPress repository, it still requires the vendor files which composer installs.

**Comment by sgatz** [comment] 2016-04-11 22:44
@stuartshields @YOzaz I see you uploaded a new file to the plugin repository, but that does not install properly.  You're gonna hose a lot of people's installation as it makes the WP no longer accessible (even to disable the plugin).  Need to get that file into the distro.

**Comment by diegoquinteiro** [comment] 2016-04-12 00:17
@stuartduff that should be fixed. I've accidentally uploaded a broken version to WordPress repository. 

Can you try removing and reinstalling from the WordPress repository and check if that works?

**Comment by stuartshields** [comment] 2016-04-12 00:37
@diegoquinteiro Yes that's resolved it. I also think your autocomplete on my name is getting confused with someone else.

**Closed** 2016-04-12 02:02 UTC

**Comment by khanroar** [comment] 2017-11-13 14:19
In my i simply write this parameter define('WP_MEMORY_LIMIT', '128M'); AFTER THIS PARAMETER define('DB_COLLATE', ''); in wp-config.php file. it resolved my issue.
