### ISSUE TITLE
cant login to facebook on step 2

### ISSUE THREAD

**Issue by sumair52** [Automattic/facebook-instant-articles-wp#565] opened 2016-12-21 12:03 UTC
# Steps required to reproduce the problem

1 Install, activate plugin. 
2.Connect app with ID and secret 
3. Attempt to login to facebook, accept the dialogue messages on facebook
4. Get redirected back to the setup screen, 'login with facebook' button persists, preventing selection of facebook page

# Expected Result

* Move on to next step so a facebook page can be selected 

# Actual Result

* Stuck in , unable to select facebook page. When redirected back to the setup screen,

---

**Version Info**

* Plugin version: 3.2.2
* WordPress version: 4.7
* PHP version:

**Comment by diegoquinteiro** [comment] 2016-12-22 04:32
Hello @sumair52,

Are you logging in with the same user as the owner/creator of the App?

**Comment by sumair52** [comment] 2016-12-22 09:32
Yes I am sure that I am logging in with the same account it is a known problem i read threads about this but in the threads i cant find solution help me ASAP

**Comment by trebor3377** [comment] 2016-12-30 06:18
Hi there:

I have been experiencing the same issue where it looks like the plugin is no longer connecting with the Facebook servers. Two issues I noticed:

1. Similar to the original issue outlined above when navigating to the plugin settings screen it shows a message "App connected". Beneath that there is a Login with Facebook button instructing you to log into your Facebook account to finish connecting to the Instant Articles Plugin to your account. When the login button is clicked on an error screen is returned "Sorry, something went wrong". This appears to be an OAuth general error screen from Facebook.

2. Beneath the login button on the settings screen there is a link for opening advanced settings ("Already set up?). Clicking this link shows all of my settings for the plugin, however the settings are grayed out and the spinning loading icon spins indefinitely. Again it looks like the plugin is not connecting to the Facebook servers.

Any ideas on how to resolve this? I noticed several other posters on the Word Press boards for the plugin are reporting the same issue. According to the client who runs the site which is using the plugin, the plugin has not been publishing articles successfully since November 8th 2016.

Hope the above information is helpful and if anyone has a fix it would be greatly appreciated. Thanks!

**Comment by michalzadkowski** [comment] 2017-01-05 15:53
Same problem here. Using 3.2.2.
I set up two separate blogs, on one everything works flawlessly, on the second I' stuck on FB login button. All steps (installation, app creation etc.) were identical. The blog where it fails, is on https, but I doubt this is correlated.

Honestly, I am very confused - no idea why it works on one site, while on the other it fails.

**Comment by michalzadkowski** [comment] 2017-01-10 09:33
I have upgraded to 3.3. Unfortunately the problem persists. And from what I can see it is a recurring one. I could find it described in #565, #561, #454. So I believe this is not exactly news for you.

I'd like to help, please show me how

**Comment by doodkat** [comment] 2017-01-11 21:37
Just upgraded to 3.3 but issues still persist. Anyone have any idea? Should I uninstall the WP plug-in and re-install it? Possibly change the FB App associated? I'm at a complete loss.

**Comment by cakobox** [comment] 2017-01-18 06:44
Try add Valid OAuth redirect URIs https://domain.com/wp-admin/admin.php?page=instant-articles-wizard at Facebook Login > Settings as temporary solution.

**Comment by michalzadkowski** [comment] 2017-01-18 08:52
Ok, after being ignored by the authors (sorry, not trying to be mean, just frustrated), I asked my friends to look into this problem. Here's the solution that worked for us:

When the plugin requests the access_token from FB, it uses graph-sdk from vendor to create an redirect url to return the token. There's a FacebookUrlDetectionHandler.php file in graph-sdk and in line 141 a default value for a port is determined - which is a `$_SERVER[‘SERVER_PORT’]` variable from wp-config.php. In our case this variable's value was set to `80`, despite using `https` protocol.

So, the solution (in our case) was to set `$_SERVER['SERVER_PORT'] = '443';` in `wp-config.php`


BTW, can you guys confirm that all of you having problems on step 2 are using https? Or this was just a lucky shot.

**Comment by cakobox** [comment] 2017-01-21 06:07
Yes. I am using https.

**Comment by akirasethi88** [comment] 2017-01-22 13:52
@diegoquinteiro 

![cropped](https://cloud.githubusercontent.com/assets/25280459/22182767/7f589744-e0d3-11e6-9a27-b9ef73e2a400.png)

Under "Facebook Instant Articles Settings" I'm unable to select Facebook page. I get redirected back to the same setup screen.

version:
Wordpress: 4.7.1
Plugin: 3.3

please, solve this issue!!

**Comment by webbvt** [comment] 2017-01-23 17:06
![screen shot 2017-01-23 at 11 58 21 am](https://cloud.githubusercontent.com/assets/25303871/22213941/041014ea-e164-11e6-9163-53aab4176c5a.png)
![screen shot 2017-01-23 at 11 57 51 am](https://cloud.githubusercontent.com/assets/25303871/22213950/0b1b3026-e164-11e6-93df-858d7303fc53.png)
WP: 4.7.1
Plugin: 3.3

Attempt to login w Facebook. Get error mes.
Open Advanced Settings leads to a never-ending loading cycle

**Comment by thejavangumalli** [comment] 2017-02-15 23:31
@michalzadkowski  We are on http and seeing this issue.
Anyone else figured out the cause for this? Works fine on the staging but not on our prod site

**Comment by everton-rosario** [comment] 2017-02-17 12:58
@sumair52 @thejavangumalli @webbvt @akirasethi88 @cakobox @doodkat @michalzadkowski @trebor3377 We are working on a new ingestion flow that will remove the need of using APP ID + Login, which will make this error vanish away.
The PR we are working is this one: https://github.com/Automattic/facebook-instant-articles-wp/pull/548

Meanwhile to try to get rid of this issue on the login/permissions:
1. Make sure you are admin of the page
2. Make sure that on that browser you are accessing the wordpress, you have been logged with the Facebook user that is Admin of the page you are setting
3. Make sure you are copying the correct APP_ID and APP_SECRET
4. Make sure the claimed URL on IA matches the domain of page on the login flow
5. Remove any old data from the fields stored in the WordPress
6. Make sure you are using one of the latest versions of Wordpress, plugin and a compatible PHP Version

Hope any of these steps works for you guys.

This login flow is a feature that won't be changed, since it will be removed from the plugin.
Soon we will release this new flow for beta testers. Feel free to join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
The beta testers will be selected there, before making this feature public.

Closing for now, but you still can use this thread for discussion.

**Closed by everton-rosario** 2017-02-17 12:58 UTC
Labels: wontfix

**Comment by tr33m4n** [comment] 2017-08-24 12:23
I know this is an old issue now, but some clients just don't like paying for upgrades! Using v3.3.3 of the plugin, we also had the port issue mentioned by @michalzadkowski 

We solved by setting the `HTTP_X_FORWARDED_PROTO` header to `https`. The function `\Facebook\Url\FacebookUrlDetectionHandler::getCurrentPort` in the FB SDK checks for a port in `HTTP_X_FORWARDED_PORT`, if not present it will try and determine whether the site is using `https` from the `HTTP_X_FORWARDED_PROTO` header, then set the port to `443`. Failing that it will fall back to `HTTP_SERVER_PORT`. FYI for anyone in the future
