### ISSUE TITLE
The post is not submitting to Instant Article

### ISSUE THREAD

**Issue by FagnerCA** [Automattic/facebook-instant-articles-wp#601] opened 2017-02-01 11:37 UTC
# Steps required to reproduce the problem

1. When I write a post, it is showing a problem with the transformation: No rules defined for `<div class="pf-content">` in the context of InstantArticle 
2. I have tried to set up a new transformation rule, making this:
```json
{
  "class": "IgnoreRule",
  "selector" : "div.pf-content"
}
```
# Expected Result

* The post should be submetted to Instant Article.

# Actual Result

* It is not working yet

---

**Version Info**

* Plugin version: latest
* WordPress version: 4.7.2
* PHP version: 5.6.27

**Comment by diegoquinteiro** [comment] 2017-02-03 15:06
Hi, what error message do you see? You need to resave your post in order to re-try submitting it to IA.

**Comment by FagnerCA** [comment] 2017-02-10 11:24
Hello!

It is the error message:

 This post was not yet submitted to Instant Articles. 

 This post was transformed into an Instant Article with some warnings [Learn more | Transformer rule configuration | Toggle debug information] 

No rules defined for <div class="pf-content"> in the context of InstantArticle

**Comment by andrewtb4** [comment] 2017-04-12 13:28
I just attached a screen shot of the same issue. it appears on the single post page, Inside the admin.
[screen shot 2017-04-12 at 9 26 10 am](https://cloud.githubusercontent.com/assets/7117187/24959939/39025848-1f62-11e7-80c3-22a2c5cea176.png)

**Comment by Smehu** [comment] 2017-06-21 09:42
I have the same problem

**Comment by timjacobi** [comment] 2017-10-02 13:24
I cannot reproduce this with the latest version of the plugin. Please update and report if this is still an issue for you. Closing for now.

**Closed by timjacobi** 2017-10-02 13:24 UTC
Labels: More info needed
