### ISSUE TITLE
Major Bug: Images in LI tags are stripped away from RSS content

### ISSUE THREAD

**Issue by vahandev** [Automattic/facebook-instant-articles-wp#723] opened 2017-07-11 21:21 UTC
Hi put image inside li tag and look at RSS feed content. You will see image is missing.

**Comment by pestevez** [comment] 2017-11-09 17:15
Hey @vahandev,

This is not a bug, but the expected behavior. Per the [Instant Articles format documentation](https://developers.facebook.com/docs/instant-articles/reference/image/):

> The `<figure>` element representing the image must be included standalone within the body of the article (...)

In any case, you can create a custom rule to ignore the `<li>` elements and insert the image in the Instant Article as follows:

Source Markup:
```html
<ul class="image-list">
  <li>
    <img src="http://www.example.com/image1.jpg" />
  </li>
  <li>
    <img src="http://www.example.com/image2.jpg" />
  </li>
</ul>
```
Custom Rules:
```javascript
{
  "rules": [{
    "class": "PassthroughRule",
    "selector": "ul.image-list, ul.image-list li"
  }]
}
```
Transformed Markup:
```html
<html>
  <head>
    <link rel="canonical" href="http://localhost:8888/wordpress/2017/11/09/list-with-images/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>List with images</h1>
        <time class="op-published" datetime="2017-11-09T16:39:56+00:00">November 9th, 4:39pm</time>
        <time class="op-modified" datetime="2017-11-09T16:39:56+00:00">November 9th, 4:39pm</time>
        <address><a>pestevez</a></address>
      </header>
      <figure>
        <img src="http://www.example.com/image1.jpg"/>
      </figure>
      <figure>
        <img src="http://www.example.com/image2.jpg"/>
      </figure>
    </article>
  </body>
</html>
```
I will go ahead and close this issue, but feel free to reopen if you need additional information.

**Closed by pestevez** 2017-11-09 17:15 UTC
Labels: missing rule
