### ISSUE TITLE
Uncaught FacebookSDKException: Invalid Access Token

### ISSUE THREAD

**Issue by pp19dd** [Automattic/facebook-instant-articles-wp#456] opened 2016-09-13 16:17 UTC
# Steps required to reproduce the problem

1. Install plugin
2. Login to facebook via plugin
3. Don't select page for awhile (days, a week?) - presuming some kind of a token expires in this step
4. Navigate to Instant Articles menu in WP, see exception error message in the "Which Page Would You Like to Use for Instant Articles?" box.

# Expected Result

* I should be able to restart the authentication process, or otherwise reset any connected apps, or maybe edit some transformation rules.

# Actual Result

* Can't do anything with the plugin, including clearing any data and restarting the authentication process. Nothing is available to me through the interface, the pencil link for editing the app id does nothing, though it confirms that I do have a certain app ID connected.

Full error message:

`Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookSDKException' with message 'Failed to exchange short-lived access token for long-lived access token.' in /home/blogtest/public_html/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Client/Helper.php:80 Stack trace: #0 /home/blogtest/public_html/wp-content/plugins/facebook-instant-articles-wp/wizard/class-instant-articles-wizard-fb-helper.php(195): Facebook\InstantArticles\Client\Helper->getPagesAndTokens(Object(Facebook\Authentication\AccessToken)) #1 /home/blogtest/public_html/wp-content/plugins/facebook-instant-articles-wp/wizard/templates/page-selection-template.php(35): Instant_Articles_Wizard_FB_Helper->get_pages() #2 /home/blogtest/public_html/wp-content/plugins/facebook-instant-articles-wp/wizard/templates/wizard-template.php(88): include('/home/blogtest/...') #3 /home/blogtest/public_html/wp-content/plugins/facebook-instant-articles-wp/wizard/class-instant-articles-wizard.php(2 in /home/blogtest/public_html/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Client/Helper.php on line 80`

---

** Version Info **

* Plugin version: 3.1
* WordPress version: 4.5.4
* PHP version: 5.5.34

**Comment by demoive** [comment] 2016-09-15 08:24
Hi @pp19dd. Thanks for reporting this issue! We've been able to reproduce and it should be fixed with PR #458 — we're working to get a patch out before the next official release.

**Comment by imaddima** [comment] 2016-09-17 07:01
I have the same issue please help me

Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->d in /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php on line 89

**Comment by demoive** [comment] 2016-09-21 11:05
@pp19dd @imaddima Just dropping a note that v3.1.3 is out and available for download. Upgrading the plugin to the latest version should resolve the problem!

**Comment by imaddima** [comment] 2016-09-22 03:44
Iam running on 3.1.3 wordpress 4.6 but I have the same issue. 

Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->d in /home/content/p3pnexwpnas06_data01/43/3265743/html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php on line 89

**Comment by littlelives-rod** [comment] 2016-09-26 05:12
I'm also running plugin version 3.1.3 on wordpress 4.6.1 having the same issue. Is there a work around while we wait for the updates?

**Comment by demoive** [comment] 2016-09-26 10:25
@imaddima thanks for the output message of the error related to your problem. It appears as if the reason for your invalid access token is related to "changed password". For the time being, let's continue the discussion/investigation in #471.

@littlelives-rod is your issue related to a "changed password" problem as well? If so, follow #471. If not, could you report a new issue with some more information to the error's you're seeing?

Thanks both, and sorry for the confusion.

**Comment by demoive** [comment] 2016-09-26 14:26
@imaddima @littlelives-rod I've reopened this issue — and renamed it — to deal with the specific exception that you are experiencing. We'll comment with updates as progress is made on reproducing and getting a fix out.

**Comment by littlelives-rod** [comment] 2016-09-27 01:33
@demoive Thanks man! I was just about to send you the error message I was getting.

**Comment by demoive** [comment] 2016-09-27 06:19
You're welcome, @littlelives-rod. If it's different from @imaddima's, please send it over anyway.

**Comment by littlelives-rod** [comment] 2016-09-27 06:25
@demoive thanks It looks the same though... the problem is our WP site has multiple users and they will change passwords at will... Thanks for looking into this!
Error message
Facebook\Exceptions\FacebookResponseException: Uncaught exception 'Facebook\Exceptions\FacebookResponseException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /var/www/blog/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:89

**Comment by demoive** [comment] 2016-09-27 07:58
Thanks @littlelives-rod. This error isn't related to the WordPress password (if that's what you were referring too) so your users will be able to change their password without affecting the plugin.

**Comment by littlelives-rod** [comment] 2016-09-27 08:05
Oh yeah you're right @demoive, sorry I misread the error...

**Comment by everton-rosario** [comment] 2016-09-27 19:33
Hey just a heads up that I have this PR #481 that should fix all reported issues on this thread.

Sorry for the long wait. We will do the best we can to release this ASAP.

**Closed** 2016-10-05 14:21 UTC

**Comment by demoive** [comment] 2016-10-13 15:27
@pp19dd @imaddima @littlelives-rod v3.2 was been released earlier this week which contains the fix. Can you confirm that after upgrading, you no longer experience the issue?

**Comment by littlelives-rod** [comment] 2016-10-14 00:54
Yeah just updated yesterday... will test it... but so far so good...

**Comment by ugumuw** [comment] 2017-06-09 16:41
I have been having the same problem for around a year now. 

Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.

I thought I could delete the app and start again. But now I cannot even verify a new app token. This is the error I get

Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating application. Application has been deleted.' in /home/sakase89/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:106 Stack trace: #0 /home/sakase89/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/sakase89/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/sakase89/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /home/sakase89/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(225): F in /home/sakase89/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 106
