### ISSUE TITLE
Uncaught exception when facebook password is changed breaks plugin list and settings

### ISSUE THREAD

**Issue by eperezf** [Automattic/facebook-instant-articles-wp#495] opened 2016-10-10 02:58 UTC
# Steps required to reproduce the problem

1. Have Instant Articles configured as normal
2. Change the password of the user who authorized and created the apps
3. Try to enter the plugin list or instant articles settings on wp-admin

# Expected Result

* An error and option to reauthenticate the user.

# Actual Result

* Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /home/pisapa5/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /home/pisapa5/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/pisapa5/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/pisapa5/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /home/pisapa5/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/php- in /home/pisapa5/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php on line 89

---

** Version Info **

* Plugin version: 3.1.3
* WordPress version: 4.6.1
* PHP version: 5.5.30

**Comment by demoive** [comment] 2016-10-10 08:26
Thanks for reporting this issue, @eperezf. I see it's a duplicate of #471/#456 and was resolved by #481 which was already been merged to master so you can grab the update from the repo or wait until the next version release (expected this week).

---

Additionally, if you are able to access the "All Settings" page for your WordPress installation there is a workaround:

- Make sure you have the latest plugin version (currently v3.1.3)
- Navigate to `/wp-admin/options.php` of your installation
- Clear out the value of the option named `instant-articles-current-state`
- Click the "Save Changes" button at the bottom

This will force the plugin to revert to it’s initial state for the Setup Wizard which will avoid the Fatal error you experienced.

**Closed by demoive** 2016-10-10 08:26 UTC
Labels: duplicate

**Comment by eperezf** [comment] 2016-10-11 23:21
Version 3.2 still has this issue and `instant-articles-current-state` is not present in `/wp-admin/options.php`

**Comment by demoive** [comment] 2016-10-12 06:39
Thanks @eperezf. If the `instant-articles-current-state` option isn't available, clearing out `` and `` should have the same effect.

I'm looking into your report of this issue still occurring on v3.2. I will try to reproduce first and then follow up with you.

**Comment by everton-rosario** [comment] 2016-10-12 14:48
@eperezf I've tried to reproduce your problem by changing facebook password and some more token invalidations types (like changing APP token and deleting the app) and all was successfully reset and reconfigured.

Can you please do a small test on your environment:
* Create a new vanila installation of the WP (in a parallel environment) and add the plugin 3.2 . 
* Check if the the keys `instant-articles-*` are present on the `/wp-admin/options.php`

Let me know if this works to you.

**Comment by demoive** [comment] 2016-10-12 20:07
@eperezf another useful resource here for testing is the [**Access Token Debugger**](https://developers.facebook.com/tools/debug/accesstoken). Can you put your access token in there and share the results? I'm particularly interested in the "Valid" field to see if it produces the same error.

You can grab the access token from the `instant-articles-option-fb-page` option in the *All Settings* page (located at `/wp-admin/options.php` of your WordPress URL).

**Comment by eperezf** [comment] 2016-10-12 20:16
@demoive I deleted the old access token and replaced it with a new one to setup everything again. Everyhing seems to be working correctly now. I did use the Access Token Debugger with the old token but I can't remember what did the "Valid" field value was.

**Comment by demoive** [comment] 2016-10-13 11:05
@eperezf Glad to hear it's working now.

Any chance you can go back in your browser's history to see the status of the original token? I think the token is placed in the query parameter so it might still be available in your history. Just for peace of mind :-)

**Comment by sahilamanu** [comment] 2017-01-06 12:35
Haai all,
Even on latest version the issue is there. but i got another way to fix the same. please do note @cusatxpress

i used the method described by @demoive 


 if you are able to access the "All Settings" page for your WordPress installation there is a workaround:

1. Make sure you have the latest plugin version (currently [**v3.3**](https://github.com/Automattic/facebook-instant-articles-wp/releases/tag/3.3))
2. Navigate to `/wp-admin/options.php` of your installation
3. Clear out the value of the option named `instant-articles-current-state`
if you cant find `instant-articles-current-state` clearing out `instant-articles-option-fb-app` and `instant-articles-option-fb-page` should have the same effect.
4. Click the "Save Changes" button at the bottom.

if it doesnt work for you then,

1. Go to PhpMyadmin.
2. Choose your database.
3. Go to `wp-options` table in your database.
4. Scroll it you find  `instant-articles-option-fb-app` and `instant-articles-option-fb-page`.
5. Clear the value in `instant-articles-option-fb-app` and `instant-articles-option-fb-page` and save.

This will force the plugin to revert to it’s initial state for the Setup Wizard which will avoid the Fatal error you experienced.

6. Now go back to `siteurl/wp-admin/plugins.php` and it will load all the plugins as normal. Attached screenshot : http://prnt.sc/ds6zn1

**This worked for me.** thus closing #558 



and now revalidate again using Facebook to use [**Facebook Instant Articles for WP**](https://github.com/Automattic/facebook-instant-articles-wp/). : http://prntscr.com/ds6zrb

**Comment by dan-eth** [comment] 2017-02-08 00:58
I applied the steps recommended by @Sahilamanu twice. I even deleted the plugin; cleared the instant-articles-fb-app, instant-articles-fb-page, instant-articles-current-state files on phpMyadmin and reinstalled the plugin. 

The problem persisted. However, this time on another subsite. I am using the plugin on a multisite with five subsites.

The first is just index/front site. Set to non-index.
So, after I completed the instant articles setup wizard on the front site and two more subsites, on the fourth subsite, the wizard fails. 

I tried activating the plugin on each subsite separately, skipping the front site. Same problem occurs on the third subsite. 

There is nothing different on this subsite. And it was not the one with this problem before.

I am wondering if the plugin limits the number of subsites on a multisite OR whether there is another file that I need to clear.

--------------

I also checked the access tokens as @demoive advised. Both the user access token at the instant-articles-fb-app and the page access token at the instant-articles-fb-page. Both are Valid=true. I am not pro. But don't see warning.
------------

[I don't know if I should have started a new thread. Seemed better to follow up this thread]

**Comment by dan-eth** [comment] 2017-02-09 23:06
Ok. Here is an update if someone would help:

I noticed that:
On the two troubled subsites,
-> the instant_articles_current_state files are missing on phpMyadmin
-> the instant_articles_fbrlh_state files contain different access tokens (I checked them on access token debugger - got white page/blank page).

What do I do now?
- the missing instant-articles-current-state pages
- the contents of instant_articles_fbrlh_state files

Thanks in advance.

**Comment by dan-eth** [comment] 2017-02-10 18:38
@sahilamanu 
On  phpMyadmin, on wp-options database:

It might also be useful to clear the instant-articles-current-state and the instant_articles_fbrlh_state 

If it is multisite, it is good to check and clear the database of each subsite even if the plugin was network activated/deactivated.

[Just sharing my findings after fixing it with no response from the pros on this thread]

**Comment by sahilamanu** [comment] 2017-02-10 19:20
@Daniel,
Sorry i was on a vaction and i couldnt reply you.  You could have cleared
the values in database via phpmyadmin.  Facebook hasnt provided any update
for this issue till now,  i guess..

I hope your issue is solved  for now..

**Comment by dan-eth** [comment] 2017-02-11 00:25
@sahilamanu 
My comment is a supplement to your instruction above - which was very helpful but didn't advise on clearing instant_articles_fbrlh_state (It may not be obvious for novice people)

Thanks for your time.

**Comment by prhomhyse** [comment] 2017-02-11 13:19
I had the same issue, immediately I changed my password to Facebook and removed it from all apps and services, I had the white screen of death. 

After turning on WP Debug, I found it was caused by Instant articles. 

As @demoive suggested, I am back at the initial state, and errors are gone.
