### ISSUE TITLE
rules problem

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#603] opened 2017-02-04 21:02 UTC
I have several problems with the rules:

1. No rules defined for `<div class="fotorama--wp">` in the context of InstantArticle
Install plugin fotorama
2. No rules defined for `<div>` in the context of InstantArticle
3. No rules defined for `<div class="fb-post">` in the context of InstantArticle
Insert facebook post

---

**Version Info**

* Plugin version: 3.3.1 
* WordPress version: 4.7.2
* PHP version: 7.0.12

**Comment by lubimow** [comment] 2017-05-13 07:24
@diegoquinteiro Help solve this problem.

**Comment by off-bank** [comment] 2017-05-13 19:33
Like number 2 above (No rules defined for <div> in the context of InstantArticle), how to convert a div without a class?

**Comment by lubimow** [comment] 2017-07-01 06:24
@diegoquinteiro Hello. Did not you find a solution to my problem?

**Comment by timjacobi** [comment] 2017-10-03 15:20
Duplicate of #582

Please continue the discussion there.

**Closed by timjacobi** 2017-10-03 15:20 UTC
Labels: help wanted, Transformation
