### ISSUE TITLE
No rules defined for fb-root

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#575] opened 2016-12-30 17:10 UTC
I bet after updating the plugin to appear this error:
`No rules defined for <div> in the context of InstantArticle` (when you hover on the error he writes this: `<div id=”fb-root”></div>`)
`No rules defined for <div class=”fb-post”> in the context of InstantArticle`

what to do?

**Version Info**

* Plugin version: 3.2.2
* WordPress version:  4.7
* PHP version:  7.0.8

**Comment by jppgks** [comment] 2017-01-01 14:07
@lubimow https://github.com/Automattic/facebook-instant-articles-wp#frequently-asked-questions

**Comment by timjacobi** [comment] 2017-10-02 14:37
Duplicate of #582

**Closed by timjacobi** 2017-10-02 14:37 UTC
Labels: compat, help wanted
