### ISSUE TITLE
Plugin integration support: Tiled Galleries Carousel Without Jetpack

### ISSUE THREAD

**Issue by demoive** [Automattic/facebook-instant-articles-wp#233] opened 2016-05-05 17:32 UTC
Add default support for the markup generated by the [Tiled Galleries Carousel Without Jetpack](https://wordpress.org/plugins/tiled-gallery-carousel-without-jetpack/) plugin.

**Source Markup**

``` html
<div class="tiled-gallery type-square tiled-gallery-unresized" data-original-width="500" data-carousel-extra='{&quot;blog_id&quot;:1,&quot;permalink&quot;:&quot;http:\/\/www.socialnews.xyz\/2016\/04\/mumbai-baaghi-filmmaker-introduce-sudheer-babu-to-media\/&quot;,&quot;likes_blog_id&quot;:100417382}' itemscope itemtype="http://schema.org/ImageGallery" >

  <div class="gallery-row" style="width: 500px; height: 500px;" data-original-width="500" data-original-height="500" >

    <div class="gallery-group" style="width: 500px; height: 500px;" data-original-width="500" data-original-height="500" >
      <div class="tiled-gallery-item" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="http://www.socialnews.xyz/4d92c03282e3df6c2683b70e24462b4d-jpg/" border="0" itemprop="url">
          <meta itemprop="width" content="496">
          <meta itemprop="height" content="496">
          <img data-attachment-id="133608" data-orig-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/4d92c03282e3df6c2683b70e24462b4d.jpg" data-orig-size="720,480" data-comments-opened="" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;IANS&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;Mumbai: Filmmaker Sabbir Khan during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;created_timestamp&quot;:&quot;1461152110&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;Mumbai: Filmmaker Sabbir Khan during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Mumbai: Filmmaker Sabbir Khan during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" data-image-description="" data-medium-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/4d92c03282e3df6c2683b70e24462b4d-300x200.jpg" data-large-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/4d92c03282e3df6c2683b70e24462b4d.jpg" src="http://i0.wp.com/www.socialnews.xyz/wp-content/uploads/2016/04/20/4d92c03282e3df6c2683b70e24462b4d.jpg?resize=496%2C496" data-original-width="496" data-original-height="496" itemprop="http://schema.org/image" title="Mumbai: Filmmaker Sabbir Khan during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" alt="Mumbai: Filmmaker Sabbir Khan during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" style="width: 496px; height: 496px;" data-recalc-dims="1" />
        </a>
        <div class="tiled-gallery-caption" itemprop="caption description">
          Mumbai: Filmmaker Sabbir Khan during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)
        </div>
      </p></div>
    </p></div>

  </p></div>

  <div class="gallery-row" style="width: 500px; height: 166px;" data-original-width="500" data-original-height="166" >

    <div class="gallery-group" style="width: 166px; height: 166px;" data-original-width="166" data-original-height="166" >
      <div class="tiled-gallery-item" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="http://www.socialnews.xyz/493408245b60f6b1c736929df925b980-jpg/" border="0" itemprop="url">
          <meta itemprop="width" content="162">
          <meta itemprop="height" content="162">
          <img data-attachment-id="133606" data-orig-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/493408245b60f6b1c736929df925b980.jpg" data-orig-size="480,720" data-comments-opened="" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;IANS&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;created_timestamp&quot;:&quot;1461152108&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" data-image-description="" data-medium-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/493408245b60f6b1c736929df925b980-200x300.jpg" data-large-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/493408245b60f6b1c736929df925b980.jpg" src="http://i2.wp.com/www.socialnews.xyz/wp-content/uploads/2016/04/20/493408245b60f6b1c736929df925b980.jpg?resize=162%2C162" data-original-width="162" data-original-height="162" itemprop="http://schema.org/image" title="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" alt="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" style="width: 162px; height: 162px;" data-recalc-dims="1" />
        </a>
        <div class="tiled-gallery-caption" itemprop="caption description">
          Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)
        </div>
      </p></div>
    </p></div>

    <div class="gallery-group" style="width: 166px; height: 166px;" data-original-width="166" data-original-height="166" >
      <div class="tiled-gallery-item" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="http://www.socialnews.xyz/6e802a7eb9a60669da8f2332129d97e4-jpg/" border="0" itemprop="url">
          <meta itemprop="width" content="162">
          <meta itemprop="height" content="162">
          <img data-attachment-id="133607" data-orig-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/6e802a7eb9a60669da8f2332129d97e4.jpg" data-orig-size="480,720" data-comments-opened="" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;IANS&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;created_timestamp&quot;:&quot;1461152108&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" data-image-description="" data-medium-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/6e802a7eb9a60669da8f2332129d97e4-200x300.jpg" data-large-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/6e802a7eb9a60669da8f2332129d97e4.jpg" src="http://i1.wp.com/www.socialnews.xyz/wp-content/uploads/2016/04/20/6e802a7eb9a60669da8f2332129d97e4.jpg?resize=162%2C162" data-original-width="162" data-original-height="162" itemprop="http://schema.org/image" title="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" alt="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" style="width: 162px; height: 162px;" data-recalc-dims="1" />
        </a>
        <div class="tiled-gallery-caption" itemprop="caption description">
          Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)
        </div>
      </p></div>
    </p></div>

    <div class="gallery-group" style="width: 166px; height: 166px;" data-original-width="166" data-original-height="166" >
      <div class="tiled-gallery-item" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="http://www.socialnews.xyz/7334361417bc17e8b273850194d79f34-jpg/" border="0" itemprop="url">
          <meta itemprop="width" content="162">
          <meta itemprop="height" content="162">
          <img data-attachment-id="133609" data-orig-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/7334361417bc17e8b273850194d79f34.jpg" data-orig-size="480,720" data-comments-opened="" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;IANS&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;created_timestamp&quot;:&quot;1461152112&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" data-image-description="" data-medium-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/7334361417bc17e8b273850194d79f34-200x300.jpg" data-large-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/7334361417bc17e8b273850194d79f34.jpg" src="http://i0.wp.com/www.socialnews.xyz/wp-content/uploads/2016/04/20/7334361417bc17e8b273850194d79f34.jpg?resize=162%2C162" data-original-width="162" data-original-height="162" itemprop="http://schema.org/image" title="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" alt="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" style="width: 162px; height: 162px;" data-recalc-dims="1" />
        </a>
        <div class="tiled-gallery-caption" itemprop="caption description">
          Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)
        </div>
      </p></div>
    </p></div>

  </p></div>

  <div class="gallery-row" style="width: 500px; height: 166px;" data-original-width="500" data-original-height="166" >

    <div class="gallery-group" style="width: 166px; height: 166px;" data-original-width="166" data-original-height="166" >
      <div class="tiled-gallery-item" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="http://www.socialnews.xyz/a747599cb55fde3bd8c4da3a39b05a31-jpg/" border="0" itemprop="url">
          <meta itemprop="width" content="162">
          <meta itemprop="height" content="162">
          <img data-attachment-id="133610" data-orig-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/a747599cb55fde3bd8c4da3a39b05a31.jpg" data-orig-size="480,720" data-comments-opened="" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;IANS&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;created_timestamp&quot;:&quot;1461152112&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" data-image-description="" data-medium-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/a747599cb55fde3bd8c4da3a39b05a31-200x300.jpg" data-large-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/a747599cb55fde3bd8c4da3a39b05a31.jpg" src="http://i2.wp.com/www.socialnews.xyz/wp-content/uploads/2016/04/20/a747599cb55fde3bd8c4da3a39b05a31.jpg?resize=162%2C162" data-original-width="162" data-original-height="162" itemprop="http://schema.org/image" title="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" alt="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" style="width: 162px; height: 162px;" data-recalc-dims="1" />
        </a>
        <div class="tiled-gallery-caption" itemprop="caption description">
          Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)
        </div>
      </p></div>
    </p></div>

    <div class="gallery-group" style="width: 166px; height: 166px;" data-original-width="166" data-original-height="166" >
      <div class="tiled-gallery-item" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="http://www.socialnews.xyz/049458fac2f4c0b0a2f54dac9f1455e2-jpg/" border="0" itemprop="url">
          <meta itemprop="width" content="162">
          <meta itemprop="height" content="162">
          <img data-attachment-id="133611" data-orig-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/049458fac2f4c0b0a2f54dac9f1455e2.jpg" data-orig-size="480,720" data-comments-opened="" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;IANS&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;created_timestamp&quot;:&quot;1461152112&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" data-image-description="" data-medium-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/049458fac2f4c0b0a2f54dac9f1455e2-200x300.jpg" data-large-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/049458fac2f4c0b0a2f54dac9f1455e2.jpg" src="http://i2.wp.com/www.socialnews.xyz/wp-content/uploads/2016/04/20/049458fac2f4c0b0a2f54dac9f1455e2.jpg?resize=162%2C162" data-original-width="162" data-original-height="162" itemprop="http://schema.org/image" title="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" alt="Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" style="width: 162px; height: 162px;" data-recalc-dims="1" />
        </a>
        <div class="tiled-gallery-caption" itemprop="caption description">
          Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)
        </div>
      </p></div>
    </p></div>

    <div class="gallery-group" style="width: 166px; height: 166px;" data-original-width="166" data-original-height="166" >
      <div class="tiled-gallery-item" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="http://www.socialnews.xyz/fe432702719b1e097853c6e6e24ae721-jpg/" border="0" itemprop="url">
          <meta itemprop="width" content="162">
          <meta itemprop="height" content="162">
          <img data-attachment-id="133613" data-orig-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/fe432702719b1e097853c6e6e24ae721.jpg" data-orig-size="480,720" data-comments-opened="" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;IANS&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;created_timestamp&quot;:&quot;1461150938&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" data-image-description="" data-medium-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/fe432702719b1e097853c6e6e24ae721-200x300.jpg" data-large-file="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/fe432702719b1e097853c6e6e24ae721.jpg" src="http://i0.wp.com/www.socialnews.xyz/wp-content/uploads/2016/04/20/fe432702719b1e097853c6e6e24ae721.jpg?resize=162%2C162" data-original-width="162" data-original-height="162" itemprop="http://schema.org/image" title="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" alt="Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)" style="width: 162px; height: 162px;" data-recalc-dims="1" />
        </a>
        <div class="tiled-gallery-caption" itemprop="caption description">
          Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS)
        </div>
      </p></div>
    </p></div>

  </p></div>

</p></div>
```

**Transformed Markup**

``` html
<figure class="op-slideshow">
  <figure>
    <img src="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/4d92c03282e3df6c2683b70e24462b4d.jpg"/>
    <figcaption> Mumbai: Filmmaker Sabbir Khan during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS) </figcaption>
  </figure>
  <figure>
    <img src="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/493408245b60f6b1c736929df925b980.jpg"/>
    <figcaption> Mumbai: Filmmaker Sabbir Khan and debut actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS) </figcaption>
  </figure>
  <figure>
    <img src="http://www.socialnews.xyz/wp-content/uploads/2016/04/20/a747599cb55fde3bd8c4da3a39b05a31.jpg"/>
    <figcaption> Mumbai: Actor Sudheer Babu during a media interaction, in Mumbai on April 19, 2016. (Photo: IANS) </figcaption>
  </figure>
</figure>
```

References:
https://wordpress.org/support/topic/gallery-pulling-only-the-first-image-in-each-row?replies=2

**Comment by demoive** [comment] 2016-05-05 17:36
Note, the transformed markup from above was successfully generated using the following Rules defined by **agk4444** on the WordPress forum. There is still a doubt as to why only 3 of the 7 images appear.

One interesting observation is that the transformed output contains only contains the images with unique captions.

```
{
    "rules":
    [

    {
        "class": "SlideshowImageRule",
        "selector" : "div.gallery-row",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "data-orig-file"
            },
             "caption.title" : {
                        "type" : "string",
                        "selector" : "div.tiled-gallery-caption"
                    }
         }
    },
   {
        "class": "SlideshowRule",
        "selector" : "div.tiled-gallery"
    }
]
}
```

**Comment by nicolinuxfr** [comment] 2016-05-05 22:11
Quick comment to add that I have many problems with Jetpack galleries too. On this post, I have some partial gallery and some with only the first one : https://voiretmanger.fr/venise/

I used the rules mentioned before.

**Comment by demoive** [comment] 2016-05-05 23:29
Thanks for the feedback, @nicolinuxfr. This issue is specifically for the **Tiled Galleries Carousel _Without Jetpack_**. By chance are you referring to one (or multiple) of the following?

https://jetpack.com/support/tiled-galleries/
https://jetpack.com/support/extra-sidebar-widgets/gallery-widget/
https://jetpack.com/support/carousel/

**Comment by nicolinuxfr** [comment] 2016-05-06 09:14
I’m referring to the first one. But unless I’m mistaken, the plugin does exactly the same think as Jetpack. Anyway, the output is roughly the same.

**Comment by stuartshields** [comment] 2016-05-30 07:42
@demoive I've adjusted your code to work with JetPack Tiled Galleries. I noticed it was only bringing in 1 image, however a simple adjustment brings in all images from the tiled gallery.

```json
{
    "rules":
    [{
        "class": "SlideshowImageRule",
        "selector" : "div.gallery-group",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "data-orig-file"
            }
         }
    },{
        "class": "SlideshowRule",
        "selector" : "div.gallery-row"
    }]
}

**Comment by pmfadil** [comment] 2016-05-31 09:53
Hello @stuartshields. Does it work for you?
For me, there's still the warning below and the gallery is not transformed at all. 
No rules defined for <div class="tiled-gallery type-rectangular tiled-gallery-unresized"> in the context of InstantArticle

**Comment by diplatis** [comment] 2016-06-24 10:48
@pmfadil I get the same error. Any progress?

**Comment by timjacobi** [comment] 2017-10-03 15:21
Duplicate of #582

Please continue the discussion there.

**Closed by timjacobi** 2017-10-03 15:21 UTC
Labels: compat
