### ISSUE TITLE
No rules defined for <div class="entry-content"> in the context of InstantArticle

### ISSUE THREAD

**Issue by littlesunn** [Automattic/facebook-instant-articles-wp#652] opened 2017-03-26 01:47 UTC
No rules defined for <div class="entry-content"> in the context of InstantArticle

but i have full article with text picture and etc, please help me

* Plugin version: 3.3.3
* WordPress version: 4.7.3

**Comment by rajumahto** [comment] 2017-08-10 18:27
hi i am also facing same issue but don't get any solutions .....plz help

**Comment by emlynn8722** [comment] 2017-08-23 20:08
Any solutions for this? Having the same problem.

**Comment by timjacobi** [comment] 2017-10-03 15:19
Duplicate of #582

Please continue the discussion there.

**Closed by timjacobi** 2017-10-03 15:19 UTC
