### ISSUE TITLE
Exclude a category from auto-publishing to FB IA

### ISSUE THREAD

**Issue by davidfilat** [Automattic/facebook-instant-articles-wp#662] opened 2017-04-13 09:25 UTC
I face a problem, I'm using a plugin for auto-publishing Youtube Videos in wordpress posts and when they are added as FB IA, the videos are not displayed. It would be very useful if we could exclude some categories from being auto-published to FB IA. Thank you for your hard work!

**Comment by timjacobi** [comment] 2017-10-04 16:29
Duplicate of #186

**Closed by timjacobi** 2017-10-04 16:29 UTC
