### ISSUE TITLE
Facebook Comments Plugin And Instant Articles for WP Compatibility Issue

### ISSUE THREAD

**Issue by onlinetushar** [Automattic/facebook-instant-articles-wp#846] opened 2017-12-25 16:50 UTC
Please check screenshot ( https://ibb.co/ne75Pm ) and suggest how to solve this error?

Site URL: https://www.missionmpsc.com/

* Instant Articles for WP Plugin version: 4.0.6
* Facebook Comments Plugin version: 2.3.6
* WordPress version: 4.9.1
* PHP version: 7

Without the above information we are not able to debug the issue and will close it.

**Comment by diegoquinteiro** [comment] 2017-12-27 17:07
Thanks @onlinetushar for reaching out. It is very weird that these two elements are being added to the content body. I'll try to reproduce it on my side. Meanwhile, a quick fix is going to the Instant Articles plugin settings, and adding the following Custom Transformer Rules:

```json
{
    "rules":[
        { "class": "IgnoreRule", "selector": ".fb-comments" },
        { "class": "IgnoreRule", "selector": "comments-count" }
    ]
}
```

Let me know if that works.

**Comment by pestevez** [comment] 2018-01-05 20:03
Hey @onlinetushar,

Facebook Comments plugin is a third-party plugin, which we currently don't support. Since it is also no longer supported by its author I am not sure if we ever will support it, but we will gladly review any related pull requests.

My recommendation is for you to use the rules recommended by @diegoquinteiro; but also that you share your Source Markup, Transformed Markup, custom rules (if any), and the expected result for any of us to be able to help.

**Comment by beeriz** [comment] 2018-01-06 15:25
```
{
  "rules": [
     {
     "class": "IgnoreRule", 
     "selector": ".fb-comments" 
     },
      {
      "class": "IgnoreRule", 
      "selector": "#wpdevar_comment_4" 
      }
  ]
}

```

This worked for me.

**Comment by mburak** [comment] 2018-01-15 13:24
Closing as the suggested rules worked.

**Closed by mburak** 2018-01-15 13:24 UTC
Labels: compat: 3rd party
