### ISSUE TITLE
this plugin needs to be updated for "Recirculation Ad Units"

### ISSUE THREAD

**Issue by ramseymohsen** [Automattic/facebook-instant-articles-wp#692] opened 2017-06-20 23:45 UTC
Facebook released this feature: https://developers.facebook.com/docs/instant-articles/monetization/ad-placement#recirculation-units

Can you guys please update the plugin to inject this tag to the end of articles?

**Comment by alexsshoelovers** [comment] 2017-06-26 20:50
Hi, in case you are interested, I solved it by adding a Meta Property using the instant_articles_transformed_element filter. 


add_filter( 'instant_articles_transformed_element','m_add_recirculation_ad' );
function m_add_recirculation_ad ($instant_article) {
    $instant_article->addMetaProperty('fb:op-recirculation-ads', 'placement_id=YOUR_PLACEMENT_ID');
    return $instant_article;
}

**Comment by mrgrupbg** [comment] 2017-09-13 09:02
Hi, @alexsshoelovers This solution is not working!

**Comment by timjacobi** [comment] 2017-10-04 15:13
Duplicate of #763

**Closed by timjacobi** 2017-10-04 15:13 UTC
