### ISSUE TITLE
Plugin doesn't pass <figure> ad code through to IA output

### ISSUE THREAD

**Issue by pnoeric** [Automattic/facebook-instant-articles-wp#779] opened 2017-10-04 16:25 UTC
# Steps required to reproduce the problem

1. Look at the original article: http://afv.com/12-reasons-two-is-better-than-one/
2. Click "view source" and search for `<figure class="op-ad">`
3. Look at output of WP plugin: http://afv.com/feed/instant-articles
4. Notice the entire `<figure>` from of the original content isn't there! (Search for `op-ad` and you get no results)

# Expected Result

* All the content from the original post would be converted into IA format and output by the plugin

# Actual Result

* The IA plugin ignores the entire `<figure>` and doesn't put it in the final output

---

**Version Info**

* Plugin version:  4.0.5
* WordPress version: 4.8.2

**Comment by pnoeric** [comment] 2017-10-04 16:38
At the bottom of my post, I see this error message:

*Invalid selector for fields (image.url). The node being transformed was <figure> in the context of InstantArticle within the Rule ImageRule with these properties: { image.url=StringGetter}*

This is the code I'm trying to insert:
`<figure class="op-ad"><iframe style="border: 0; margin: 0;" src="https://www.facebook.com/adnw_request?placement=1328186133977689_1328212680641701&amp;adtype=banner300x250" width="300" height="250"></iframe></figure>`

Can this not be passed through?

**Comment by timjacobi** [comment] 2017-10-04 17:10
I can reproduce this. We will take a look at it.

**Comment by pestevez** [comment] 2017-11-09 02:41
Hey @pnoeric,

It looks like the source code of the article you provide as the sample does not contain the figure anymore. Was the figure you mentioned something like the following?
```html
<figure class="op-ad">
  <iframe style="border: 0; margin: 0;" src="https://www.facebook.com/adnw_request?placement=1328186133977689_1328212680641701&#038;adtype=banner300x250" width="300" height="250"></iframe>
</figure>
```
If so, by using the [IA PHP SDK default rule config](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Parser/instant-articles-rules.json) for `AdRule` in your custom rules should allow you to copy it over to the Instant Articles markup:
```javascript
{
	"class": "AdRule",
	"selector": "figure.op-ad",
	"properties": {
		"ad.url": {
			"type": "string",
			"selector": "iframe",
			"attribute": "src"
		},
		"ad.height": {
			"type": "int",
			"selector": "iframe",
			"attribute": "height"
		},
		"ad.width": {
			"type": "int",
			"selector": "iframe",
			"attribute": "width"
		},
		"ad.embed": {
			"type": "children",
			"selector": "iframe"
		}
	}
}
```
I'm not sure why this configuration is not part of the default plugin settings, though.

**Comment by pestevez** [comment] 2017-11-10 20:07
I am closing the issue now since I cannot find the mentioned `figure` in the referenced URL, and I provided a rule that may solve the problem.

Please feel free to reopen if you still face the problem or if you need additional information.

**Closed by pestevez** 2017-11-10 20:07 UTC
Labels: missing rule, more info needed
