### ISSUE TITLE
Website Minimal readership

### ISSUE THREAD

**Issue by Chekist76** [Automattic/facebook-instant-articles-wp#938] opened 2018-05-17 20:17 UTC
I am getting this error while trying to submit my website URL
"The provided URL is not being accepted because the site has minimal readership, which violates the Instant Article Policies (https://developers.facebook.com/docs/instant-articles/policy/). Please provide a different URL."

My website had an instant articles activated, had traffic and suddenly I got this error.

Also tried submitting a different website, with 10 articles and with traffic, the system did let me submit it without problems. It went on pending review, however after 8 days the site dissapeared from the list. 

The funny thing is that it still says that Your submission has been received. We're making changes to our review process, so account reviews will take 10 days or more.

But there is no URL in the list. And when I try to connect the same URL I used when submitting my application I am getting the error of minimal readership

Could you please help me?

Page ID: 1669566293365145

Thanks in advance

**Comment by jerclarke** [comment] 2018-05-21 21:37
They upended their standards and it seems now almost all sites have minimal readership by the new standards. Previously they didn't seem to enforce this rule at all. 

Someone in #925 (which this is pretty much a duplicate of) logged their specific stats as being over 100 engagements/week and still considered minimal, so that's our main reference so far. Maybe you could go there and add your comparable stats so we can build up a list of what minimal is, **SINCE THE DEVS REFUSE TO ACKNOWLEDGE THIS DISASTROUS CHANGE OR GIVE US ANY NUMBERS TO KNOW IF WE'RE CLOSE OR NOT**. 

👎SNAFU👎

**Comment by everton-rosario** [comment] 2018-06-07 00:15
Duplicate of #925

**Closed by everton-rosario** 2018-06-07 00:15 UTC
Labels: duplicated

**Comment by cruelgrimz** [comment] 2018-09-06 06:04
100k view monthly fb instant article
