### ISSUE TITLE
Image size too small

### ISSUE THREAD

**Issue by sebids** [Automattic/facebook-instant-articles-wp#157] opened 2016-04-15 09:29 UTC
Our WordPress installation's image sizes are set to 596 Pixel width for the large images.

FB now get's these really small images and when you tap on them, they are zoomed but naturally they look totally blurry.

Is there an option to have the plugin use the original image size of images in a post instead of this "large" image size?

**Comment by banago** [comment] 2016-04-18 14:40
Gallery images are two small. They are the small thumbnails in stead of a bigger image.

**Comment by banago** [comment] 2016-04-18 16:20
Found: you have to edit the size of the gallery when you insert it.

**Comment by sebids** [comment] 2016-04-19 13:32
@banago Your problem is a different one, right? I'm not talking about galleries. I meant single images.

**Comment by banago** [comment] 2016-04-19 15:48
@sebids you're right. However, I think the issue is the same technically, you insert small images in the post.

**Comment by sebids** [comment] 2016-04-19 19:02
OK, but when I have a reason to use small images in my posts, but still want to have the best image quality for Facebook, would'nt it be great, if FB would get the best possible images?

I assume, FB scales them down to optimal sizes for the devices, do they?

If that's not the case, it would make a great settings options to set the preferred image size.

**Comment by philipjohn** [comment] 2016-05-31 13:52
Am I right in thinking that you've edited the large image size using the setting in Settings > Media @sebids ? 

The plugin will grab whatever you use when creating content in the editor, so if that's the large size set at 596px, that's what'll appear in your feed.

We do have the `instant_articles_content` filter which would allow you to filter the output, but it'd be a case of searching the content for image references and adjusting them which is messy.

**Comment by sebids** [comment] 2016-05-31 14:04
Right. That's what I meant.

OK, so it takes the size used in the editor. Would still be nice to have a setting to use a larger image size.
Because manually searching the content is messy, yes.

**Comment by everton-rosario** [comment] 2016-06-27 16:56
@sebids This is related to Image processing in WP. The image we use is the one that will be shown on Web. It is a nice to have to be configurable, thus using the Raw image uploaded. 
It is enhancement, with low priority. 
Can you help us with a pull request regarding this feature?

**Comment by everton-rosario** [comment] 2016-07-29 19:07
Closing, if still needed, please reach out.

**Closed by everton-rosario** 2016-07-29 19:07 UTC
Labels: compat, enhancement

**Comment by andre4s** [comment] 2017-01-28 23:46
@everton-rosario this is proving problematic for us too — images we use on web are generally 400px wide which end up looking awful on hi-DPI mobile devices in the Instant Article.

The outputted image URLs are all hard-coded with size values by WP, but would it not be possible to strip these out for Instant Articles and let Facebook deliver the appropriate size image?

Some examples (we're using Photon by the way):
`https://i0.wp.com/www.berkeleysquares.co.uk/wp-content/uploads/2017/01/image3.jpg?resize=367%2C275&amp;ssl=1` — remove `resize` from parameters
`https://i1.wp.com/www.berkeleysquares.co.uk/wp-content/uploads/2016/10/pexels-photo-131816.jpeg?fit=940%2C627&amp;ssl=1` — remove `fit` from parameters
`https://i0.wp.com/www.berkeleysquares.co.uk/wp-content/uploads/2017/01/lll_still-01-400x252.jpg?fit=400%2C252&amp;ssl=1` — remove `-400x252` from filename **and** `fit` from parameters

**Comment by everton-rosario** [comment] 2017-02-01 14:43
@andre4s You could create a customized ImageRule class, by extending the [ImageRule](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Transformer/Rules/ImageRule.php) and treating the url to do the find/replace about the `resize` query param.

Created this Gist so you can copy/paste and edit to your case.

[Gist Example](https://gist.github.com/everton-rosario/5f0be84ee9167b4a4f8e6d8809e05802) so you can play with it.

Let me know if this works for you @andre4s

**Comment by timmygobang** [comment] 2017-10-26 12:07
Dont mean to sound rude, but how about fixing the plugin? 
my rss feed with your plugin is rendering the image links as
wp-content/uploads/2017/10/IMG_7888-150x150

so it's getting 150px square images rather than the full size image
