### ISSUE TITLE
Embedded video issues

### ISSUE THREAD

**Issue by shrugman** [Automattic/facebook-instant-articles-wp#58] opened 2016-03-14 14:16 UTC
Facebook embedded videos do not appear in the instant articles.  Is there a way to add them in Wordpress that will allow them to be formatted properly in the feed and appear in instant article?

Also, the embedded youtube video does not fit the screen on an android device.  It fits on iphone, but is too big for the screen on android.  The feed output for the video is as follows:

`<figure class="op-social"><iframe><iframe width="500" height="281" src="https://www.youtube.com/embed/fpJOeKwv1hw?feature=oembed" frameborder="0" allowfullscreen></iframe></iframe></figure>`

**Comment by kkranzo** [comment] 2016-03-22 16:37
Are you embedding in Wordpress using oEmbed (just pasting in the URL in the editor)?

You will have to use that methos in order for the plugin to convert to the correct format.

**Comment by demoive** [comment] 2016-04-12 11:09
@shrugman there has been a major version bump since this issue was reported. Could you kindly grab the latest version and see if this still reproduces?

**Comment by abdusfauzi** [comment] 2016-04-14 05:26
I can confirm that it is still result with empty `<p></p>` whenever I paste youtube/vimeo/facebook url into my text editor. It will use oEmbed for live content.

**Comment by abdusfauzi** [comment] 2016-04-14 06:20
I added the codes into my functions.php to improve social oEmbed recognition:

```
function vckt_social_embed_type( $provider_name, $url ){
    $wp_oembed = new WP_oEmbed();
	$provider_url = $wp_oembed->get_provider( $url );

    $provider_name = false;
	if ( false !== strpos( $provider_url, 'vimeo.com' ) ) {
		$provider_name = 'vimeo';
	} elseif ( false !== strpos( $provider_url, 'youtu.be' ) ) {
		$provider_name = 'youtube';
	} elseif ( false !== strpos( $provider_url, 'facebook.com' ) ) {
		$provider_name = 'facebook';
	}

    return $provider_name;
}
add_filter('instant_articles_social_embed_type', 'vckt_social_embed_type', 10, 2);
```

however, once it detected Facebook url thru oEmbed, the xml produced has `<![CDATA[ ... ]]>` around Facebook's oEmbed scripts. This broke XML as there are now double

```
<![CDATA[
    ...
    <![CDATA[ ... ]]>
    ....
]]>
```

This is the oEmbed produced.

```
<figure class="op-social"><iframe>
<div id="fb-root"/>
<p><script><![CDATA[(function(d, s, id) {  var js, fjs = d.getElementsByTagName(s)[0];  if (d.getElementById(id)) return;  js = d.createElement(s); js.id = id;  js.src = "//connect.facebook.net/ms_MY/sdk.js#xfbml=1&version=v2.3";  fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));]]></script></p>
<div class="fb-video" data-href="https://www.facebook.com/thevocket/videos/1686986014891705/" data-width="728">
<div class="fb-xfbml-parse-ignore">
<blockquote cite="https://www.facebook.com/thevocket/videos/1686986014891705/"><p><a href="https://www.facebook.com/thevocket/videos/1686986014891705/">Iklan Komersial Mesotropin</a></p>
<p>Vocket Fitness dikuasakan oleh Mesotropin HQ. Artikel lanjut di http://vckt.co/1T9WhNP</p>
<p>Posted by <a href="https://www.facebook.com/thevocket/">The Vocket</a> on 2hb Mac 2016</p>
</blockquote>
</div>
</div>
</iframe></figure>
```

Youtube and Vimeo are still **not** wrapped or embeded into render Instant Articles.

**Comment by demoive** [comment] 2016-05-06 14:14
We'll close this for now, but please re-open if you find you are still having troubles after upgrading to the latest version.

**Closed** 2016-05-06 14:32 UTC

**Comment by zubinsaira7** [comment] 2017-09-09 15:03
I am facing this issue. Even i changed the code in the Instant article as per the embeds suggestion at https://developers.facebook.com/docs/instant-articles/reference/embeds
