### ISSUE TITLE
Plugins page blank after activate plugin

### ISSUE THREAD

**Issue by tavyDesign** [Automattic/facebook-instant-articles-wp#501] opened 2016-10-13 19:04 UTC
# Steps required to reproduce the problem

1. install
2. activate
3. plugin page blank

# Expected Result

* no problem in plugins page

# Actual Result

* plugin page is blank

---

** Version Info **

* Plugin version: 3.2
* WordPress version: 4.6.1
* PHP version: 5+

**Comment by tavyDesign** [comment] 2016-10-14 11:59
Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /storage/web/andrei/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /storage/web/andrei/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /storage/web/andrei/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /storage/web/andrei/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /storage/web/andrei/public_html/wp-content/plugins/fb-instant-art in /storage/web/andrei/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 89

this is the problem i found, i think is something saved in database... i try to remove all stored from database

**Comment by tavyDesign** [comment] 2016-10-14 12:20
i removed from database wp_options values for instant aticles and now work!

**Comment by demoive** [comment] 2016-10-17 13:24
Glad that clearing out your options value resolved the problem.

Closing as this is a duplicate of #471.

**Closed by demoive** 2016-10-17 13:24 UTC
Labels: duplicate
