### ISSUE TITLE
instant article custom rule

### ISSUE THREAD

**Issue by emicrowatch** [Automattic/facebook-instant-articles-wp#721] opened 2017-07-10 06:54 UTC
# Steps required to reproduce the problem

1. No rules defined for <div class="row"> in the context of InstantArticle
2. No rules defined for <div class="row horoscope"> in the context of InstantArticle
3. No rules defined for <div class="row horoscope"> in the context of InstantArticle
4. No rules defined for <div class="row horoscope"> in the context of InstantArticle
5. No rules defined for <div class="row horoscope"> in the context of InstantArticle
6. No rules defined for <div class="row horoscope"> in the context of InstantArticle
7. No rules defined for <div class="row horoscope"> in the context of InstantArticle

**Comment by timjacobi** [comment] 2017-10-03 15:20
Duplicate of #582

Please continue the discussion there.

**Closed by timjacobi** 2017-10-03 15:20 UTC
