### ISSUE TITLE
Instagram & Twitter Embed Images not working

### ISSUE THREAD

**Issue by VivekManglani** [Automattic/facebook-instant-articles-wp#669] opened 2017-04-27 14:28 UTC
# Steps required to reproduce the problem

1. [embed width="400" height="300"]https://www.instagram.com/p/<INSTAGRAM_ID>/[/embed]
2. [embed width="400" height="300"]https://twitter.com/<TWITTER_HANDLE>/status/<TWEET_ID>[/embed] 

# Expected Result

* The Instagram/Twitter post embedded into the Instant Article with the image.

# Actual Result

* Embed works, but no image shown. Instagram displays the placeholder and text whereas Twitter displays only text.

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.4
* PHP version: 7

![whatsapp image 2017-04-27 at 22 23 20](https://cloud.githubusercontent.com/assets/6572849/25488125/cc078d24-2b98-11e7-9e30-c5e7e621488d.jpeg)
![whatsapp image 2017-04-27 at 22 23 21](https://cloud.githubusercontent.com/assets/6572849/25488124/cbc5f09e-2b98-11e7-9214-e7efbba2dc9c.jpeg)

**Comment by apollosk** [comment] 2017-05-09 11:58
I had the same issue with Instagram, it's a Jetpack related.

Solution: Go to wp-content/plugins/jetpack/modules/shortcodes and delete isntagram.php or rename it to something instagram.php.disabled. Then republish (update) the affected articles from your admin.

**Comment by VivekManglani** [comment] 2017-05-09 13:34
@apollosk I don't have Jetpack installed...

**Comment by murshid1988** [comment] 2017-05-18 17:49
For twitter, you don't have to use the actual embed code. Just copy paste the twitter url as a text in your WYSIWYG (Tweet will be automatically embedded in WP as well). Then resubmit to FB.

**Comment by lucidash** [comment] 2017-09-13 08:54
@VivekManglani  I have same issue.  Did you resolve this problem?

**Comment by timjacobi** [comment] 2017-10-04 16:17
Twitter links are actually completely broken.

**Comment by pestevez** [comment] 2017-11-10 16:20
These are my findings for **Instagram**:

I cannot reproduce using the latest version of the plugin (4.0.5):

WordPress Text Editor Content:
```
[embed width="400" height="300"]https://www.instagram.com/p/BbNjuG0DM6q/?taken-by=instagram[/embed]
```
Source Markup:
```html
<div class="embed">
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:400px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
<div style="padding:8px;">
<div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:62.5% 0; text-align:center; width:100%;">
<div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div>
</div>
<p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://www.instagram.com/p/BbNjuG0DM6q/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">Photo illustration by @_chakmkit Thanks to the magic of post-production, Chak Kit (@_chakmkit) and his wife were able to take photos of their shiba inu, Tachi, at different points along this spiral structure and combine them into one image. “I like the expressions of my doggy the most,” says Chak. “He is really cute.” 🌀🐶 #WHPpetproject</a></p>
<p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A post shared by Instagram (@instagram) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2017-11-07T23:06:09+00:00">Nov 7, 2017 at 3:06pm PST</time></p>
</div>
</blockquote>
<p><script async defer src="//platform.instagram.com/en_US/embeds.js"></script></div>
```
Transformed Markup:
```html
<html>
  <head>
    <link rel="canonical" href="http://example.com/2017/11/10/another-instagram-post/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>Another Instagram post</h1>
        <time class="op-published" datetime="2017-11-10T16:04:49+00:00">November 10th, 4:04pm</time>
        <time class="op-modified" datetime="2017-11-10T16:08:27+00:00">November 10th, 4:08pm</time>
        <address><a>user</a></address>
      </header>
      <figure class="op-interactive">
        <iframe class="no-margin">
<blockquote class="instagram-media" data-instgrm-captioned="" data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:400px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
<div style="padding:8px;">
<div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:62.5% 0; text-align:center; width:100%;">
<div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div>
</div>
<p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://www.instagram.com/p/BbNjuG0DM6q/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">Photo illustration by @_chakmkit Thanks to the magic of post-production, Chak Kit (@_chakmkit) and his wife were able to take photos of their shiba inu, Tachi, at different points along this spiral structure and combine them into one image. “I like the expressions of my doggy the most,” says Chak. “He is really cute.” 🌀🐶 #WHPpetproject</a></p>
<p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A post shared by Instagram (@instagram) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2017-11-07T23:06:09+00:00">Nov 7, 2017 at 3:06pm PST</time></p>
</div>
</blockquote>
<p><script async="" defer="defer" src="//platform.instagram.com/en_US/embeds.js"></script></p></iframe>
      </figure>
    </article>
  </body>
</html>
```
Result: The Instagram post loos fine in the Instant Article.

If instead of adding the `embed` syntax I copy the embed code from Instagram (which will not include the `<div class="embed">` in the Source Markup, I also get the same Transformed Markup as above.

Sample Instagram Embed Code:
```html
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:62.5% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://www.instagram.com/p/BbNjuG0DM6q/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">Photo illustration by @_chakmkit Thanks to the magic of post-production, Chak Kit (@_chakmkit) and his wife were able to take photos of their shiba inu, Tachi, at different points along this spiral structure and combine them into one image. “I like the expressions of my doggy the most,” says Chak. “He is really cute.” 🌀🐶 #WHPpetproject</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A post shared by Instagram (@instagram) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2017-11-07T23:06:09+00:00">Nov 7, 2017 at 3:06pm PST</time></p></div></blockquote> <script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
```
Source Markup:
```html
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
<div style="padding:8px;">
<div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:62.5% 0; text-align:center; width:100%;">
<div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div>
</div>
<p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://www.instagram.com/p/BbNjuG0DM6q/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">Photo illustration by @_chakmkit Thanks to the magic of post-production, Chak Kit (@_chakmkit) and his wife were able to take photos of their shiba inu, Tachi, at different points along this spiral structure and combine them into one image. “I like the expressions of my doggy the most,” says Chak. “He is really cute.” 🌀🐶 #WHPpetproject</a></p>
<p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A post shared by Instagram (@instagram) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2017-11-07T23:06:09+00:00">Nov 7, 2017 at 3:06pm PST</time></p>
</div>
</blockquote>
<p> <script async defer src="//platform.instagram.com/en_US/embeds.js"></script></p>
```
Transformed Markup:
Same as the one generated for `[embed]...[/embed]`

**Comment by pestevez** [comment] 2017-11-10 16:36
These are my findings for **Twitter** using the latest version of the plugin (4.0.5):

WordPress Text Editor Content:
```
[embed width="400" height="300"]https://twitter.com/facebook/status/819685391355748354[/embed]
```
Source Markup:
```html
<div class="embed">
<blockquote class="twitter-tweet" data-width="400">
<p lang="en" dir="ltr">In an effort to establish stronger ties with the news industry, we&#39;re launching The Facebook Journalism Project: <a href="https://t.co/pSxENUU9aa">https://t.co/pSxENUU9aa</a></p>
<p>&mdash; Facebook (@facebook) <a href="https://twitter.com/facebook/status/819685391355748354?ref_src=twsrc%5Etfw">January 12, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></div>
```
Transformed Markup:
```html
<html>
  <head>
    <link rel="canonical" href="http://example.com/2017/11/10/another-twitter-post/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>Another Twitter Post</h1>
        <time class="op-published" datetime="2017-11-10T16:23:51+00:00">November 10th, 4:23pm</time>
        <time class="op-modified" datetime="2017-11-10T16:23:51+00:00">November 10th, 4:23pm</time>
        <address><a>user</a></address>
      </header>
      <figure class="op-interactive">
        <iframe class="no-margin">
<blockquote class="twitter-tweet" data-width="400">
<p lang="en" dir="ltr">In an effort to establish stronger ties with the news industry, we're launching The Facebook Journalism Project: <a href="https://t.co/pSxENUU9aa">https://t.co/pSxENUU9aa</a></p>
<p>— Facebook (@facebook) <a href="https://twitter.com/facebook/status/819685391355748354?ref_src=twsrc%5Etfw">January 12, 2017</a></p></blockquote>
<p><script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p></iframe>
      </figure>
    </article>
  </body>
</html>
```
Result: The Twitter post loos fine in the Instant Article.

However, if instead of adding the embed syntax I copy the embed code from Twitter (which will not include the `<div class="embed">` in the Source Markup, I do **NOT** get the expected Transformed Markup.

Sample Twitter Embed Code:
```html
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">In an effort to establish stronger ties with the news industry, we&#39;re launching The Facebook Journalism Project: <a href="https://t.co/pSxENUU9aa">https://t.co/pSxENUU9aa</a></p>&mdash; Facebook (@facebook) <a href="https://twitter.com/facebook/status/819685391355748354?ref_src=twsrc%5Etfw">January 12, 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
Source Markup:
```html
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">In an effort to establish stronger ties with the news industry, we&#39;re launching The Facebook Journalism Project: <a href="https://t.co/pSxENUU9aa">https://t.co/pSxENUU9aa</a></p>
<p>&mdash; Facebook (@facebook) <a href="https://twitter.com/facebook/status/819685391355748354?ref_src=twsrc%5Etfw">January 12, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
```
Transformed Markup:
```html
<html>
  <head>
    <link rel="canonical" href="http://example.com/2017/11/10/another-twitter-post/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>Another Twitter Post</h1>
        <time class="op-published" datetime="2017-11-10T16:23:51+00:00">November 10th, 4:23pm</time>
        <time class="op-modified" datetime="2017-11-10T16:31:11+00:00">November 10th, 4:31pm</time>
        <address><a>user</a></address>
      </header>
      <blockquote>
In an effort to establish stronger ties with the news industry, we're launching The Facebook Journalism Project: <a href="https://t.co/pSxENUU9aa">https://t.co/pSxENUU9aa</a>
— Facebook (@facebook) <a href="https://twitter.com/facebook/status/819685391355748354?ref_src=twsrc%5Etfw">January 12, 2017</a></blockquote>
    </article>
  </body>
</html>
```
which **won't** get rendered as the expected `Interective` element in the Instant Article.

This issue can be fixed with the following custom transformer rules:
```javascript
{
  "rules": [
    {
      "class": "InteractiveRule",
      "selector": "blockquote.twitter-tweet",
      "properties": {
        "interactive.iframe": {
          "type": "multiple",
          "children": [
            {
              "type": "element",
              "selector": "blockquote"
            },
            {
              "type": "next-sibling-element-of",
              "selector": "blockquote"
            }
          ]
        }
      }
    }
  ]
}
```
I will submit a PR to remove the need to add a custom rule.

**Comment by pestevez** [comment] 2017-11-10 16:38
I'm removing the bug label since I could not repro following the steps described by @VivekManglani. I am leaving it open until we merge my PR.

**Closed** 2017-11-13 11:17 UTC
Labels: missing rule

**Comment by J0ker98** [comment] 2017-11-29 21:22
I'm actually having the same issue.

I add my twitter/instagram post links at the end of my article, they are shown correctly on my website but they disappear while they are transformed in instant articles. I'm using the latest plugin and wordpress version.

**Comment by HongPong** [comment] 2018-03-22 01:55
FYI more broadly speaking, you might want to look at different browsers. see https://support.mozilla.org/en-US/questions/1189443 & https://stackoverflow.com/questions/47363501/embedded-twitter-post-not-working-in-wordpress

It seems in some cases twitter embeds in general vary by browser: ok in "IE11, Edge, Safari and Opera, but not in Firefox, Chrome and Maxthon".

**Comment by everton-rosario** [comment] 2018-03-23 21:11
@J0ker98 or @HongPong if you are facing this issue, can you please open a new issue with proper reproducible steps?
This way we can investigate better.

Thanks for reporting.
