### ISSUE TITLE
Instant Articles suddenly not working

### ISSUE THREAD

**Issue by samborcia** [Automattic/facebook-instant-articles-wp#913] opened 2018-04-03 05:08 UTC
Two days ago my Instant Articles suddenly stopped working. In WordPress it shows it was successfully transformed to an IA like usual. I run it through the debugger and it shows "Yes" as an Instant Article. I check in my "Production Articles" tab on my Facebook page and the article shows "Live" there. However, once I post it on my Facebook page, it doesn't display as an Instant Article in the news feed. It just goes directly to my website. 

## Version Info

* Plugin version: 4.0.6
* WordPress version: 4.9.4

**Comment by jerclarke** [comment] 2018-04-03 16:39
I couldn't reproduce this myself, but didn't test it carefully. That said, several people on the [Instant Articles Open Source FB Group](https://www.facebook.com/groups/629655867187397/permalink/995679977251649/) were having the same problem: Inexplicable failure for IA version to get rendered on mobile despite everything seeming okay in WP and on the FB Page Settings backend.

**Comment by samborcia** [comment] 2018-04-04 04:04
Yes, it seems like others have the same issue too. Is there anyway to contact Facebook directly and report this?

**Comment by pestevez** [comment] 2018-04-04 13:09
Hi @samborcia - is there a sample URL you can share with us? This repo is related to the creation of the Instant Articles markup and submission to Facebook, which based on your description is working, but I can try to troubleshoot from my end to see if anything jumps at me.

**Comment by samborcia** [comment] 2018-04-04 17:13
Website: https://www.lakemchenryscanner.com
Facebook: https://www.facebook.com/LakeMcHenryScanner

**Comment by pestevez** [comment] 2018-04-04 19:45
Thanks for the links. I don't see any issues related to the IA generation. I think you should try in the recommended Facebook group. Closing this one now...

**Closed by pestevez** 2018-04-04 19:45 UTC
Labels: more info needed
