### ISSUE TITLE
I am getting this error while trying to submit my website URL

### ISSUE THREAD

**Issue by RKUNYOU** [Automattic/facebook-instant-articles-wp#943] opened 2018-05-22 08:46 UTC
I am getting this error while trying to submit my website URL
"The provided URL is not being accepted because the site has minimal readership, which violates the Instant Article Policies (https://developers.facebook.com/docs/instant-articles/policy/). Please provide a different URL."

**Comment by keralafbmedia** [comment] 2018-05-25 09:08
this same issue i am getting    "   The provided URL is not being accepted because the site has minimal readership, which violates the Instant Article Policies (https://developers.facebook.com/docs/instant-articles/policy/). Please provide a different URL.

**Comment by keralafbmedia** [comment] 2018-05-25 09:08
please help me

**Comment by jerclarke** [comment] 2018-05-25 12:50
Hi all, there is no help, or response from the developers of this plugin with regard to this issue. 

This ticket is a duplicate of #925 and should be closed, you can add yourself to the comments there if you want. 

Facebook HQ made this change and doesn't care about all the people who already had it working and for whom it's now broken, I don't think they care AT ALL about the people who didn't even have it set up yet. 

Facebook doesn't care about small developers.

**Comment by everton-rosario** [comment] 2018-06-07 00:17
#925 duplicate.

**Closed by everton-rosario** 2018-06-07 00:17 UTC
Labels: Minimum readability, duplicated
