### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by comunicacionesintegralessa** [Automattic/facebook-instant-articles-wp#419] opened 2016-08-24 16:45 UTC
# Steps required to reproduce the problem

1. 
2. 
3. 

# Expected Result

* 

# Actual Result

* 

---

** Version Info **

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by demoive** [comment] 2016-10-07 09:53
Assuming this is a request for support of footer configuration. If so, duplicate of #261.

**Closed by demoive** 2016-10-07 09:53 UTC
