### ISSUE TITLE
Plugin remove youtube video embed code

### ISSUE THREAD

**Issue by yayacannes** [Automattic/facebook-instant-articles-wp#697] opened 2017-06-23 17:45 UTC
Plugin remove youtube video embed code so no video appears on my instant articles :(

**Comment by timjacobi** [comment] 2017-10-04 14:39
Duplicate of #653

**Comment by pestevez** [comment] 2017-11-09 22:10
Hey @yayacannes, are you still facing this problem? I am not able to repro this issue using the latest version of the plugin (4.0.5) with the default rules:

WordPress Editor content (the embed code from YouTube):
```html
<iframe width="520" height="293" src="https://www.youtube.com/embed/iUdQf1aG8ro" frameborder="0" gesture="media" allowfullscreen></iframe>
```
Source Markup:
```html
<p>
  <iframe width="520" height="293" src="https://www.youtube.com/embed/iUdQf1aG8ro" frameborder="0" gesture="media" allowfullscreen>
  </iframe>
</p>
```
Transformed Markup:
```html
<html>
  <head>
    <link rel="canonical" href="http://localhost:8888/wordpress/2017/11/09/youtube-embed/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>Youtube embed</h1>
        <time class="op-published" datetime="2017-11-09T22:06:35+00:00">November 9th, 10:06pm</time>
        <time class="op-modified" datetime="2017-11-09T22:06:35+00:00">November 9th, 10:06pm</time>
        <address><a>pestevez</a></address>
      </header>
      <figure class="op-interactive">
        <iframe src="https://www.youtube.com/embed/iUdQf1aG8ro" class="no-margin" width="520" height="293"></iframe>
      </figure>
    </article>
  </body>
</html>
```
I am closing this issue now but please feel free to reopen if you still have this problem or if you need additional information.

**Closed by pestevez** 2017-11-09 22:10 UTC
