### ISSUE TITLE
Problems with HHVM

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#68] opened 2016-03-21 15:55 UTC
Using HHVM rather than PHP, sometimes the plugin would work great and sometimes out of nowhere the RSS feed will be totally blank, if I check my HHVM error.log I see this:

    \  nFatal error: Uncaught exception 'DOMException' with message 'Hierarchy Request Error' in
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/dom-transform-filters/class-instant-articles-dom-transform-filter.php: 85\ nStack trace: \n #0  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/dom-transform-filters/class-instant-articles-dom-transform-filter.php(85): DOMNode->replaceChild()\n# 1  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/dom-transform-filters/class-instant-articles-dom-transform-filter.php(49): Instant_Articles_DOM_Transform_Filter-> _transform_element()\ n #2  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/dom-transform-filters/class-instant-articles-dom-transform-filter-table.php(23): Instant_Articles_DOM_Transform_Filter->_transform_elements()\n# 3  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/class-instant-articles-dom-transform-filter-runner.php(45): Instant_Articles_DOM_Transform_Filter_Table-> run()\ n #4  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php(309): Instant_Articles_DOM_Transform_Filter_Runner::run()\n# 5  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php(219): Instant_Articles_Post-> _get_the_content()\ n #6  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/template.php(118): Instant_Articles_Post->get_the_content()\n# 7  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php(683): include()\ n #8  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/feed-template.php(29): Instant_Articles_Post->render()\n# 9  
    	/var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(83): include()\ n #10  
    	/var/www/site.com/public_html/wp-includes/plugin.php(525): instant_articles_feed()\n# 11  
    	/var/www/site.com/public_html/wp-includes/functions.php(1236): do_action()\ n #12  
    	/var/www/site.com/public_html/wp-includes/template-loader.php(37): do_feed()\n# 13  	
    	/var/www/site.com/public_html/wp-blog-header.php(16): include()\ n #14  
    	/var/www/site.com/public_html/index.php(17): include()\n# 15  
    		{  
    			main
    		}

**Comment by lesterchan** [comment] 2016-03-26 13:23
I reported this nearly 3 weeks back =) See https://github.com/Automattic/facebook-instant-articles-wp/issues/48

**Comment by gabu69** [comment] 2016-03-26 15:15
Thanks for the reply lesterchan, 

have you find any workaround meanwhile the fix?

**Comment by bjornjohansen** [comment] 2016-04-12 18:51
Duplicate of #48

**Closed by bjornjohansen** 2016-04-12 18:51 UTC
