### ISSUE TITLE
<figcaption>ALT TEXT</figcaption>

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#153] opened 2016-04-15 02:26 UTC
Sometimes im getting my ALT TEXT of my images inside the <figcaption></figcaption> and its showing up in the instant articles. 

PS I never use captions, so it takes sometimes the ALT as caption pretty much

Didnt happen in all articles but in some and I cant find why and I end up getting errors in the IA production panel like:

```
<figure><img src="http://www.example.com/wp-content/uploads/2016/04/15-CREEPY-EASTER-BUNNYS-2-646x750.jpg"><figcaption></figcaption></figure><h2>3. ¡Prometemos no portarnos mal!</h2>
The HTML element does not contain any text: Avoid including empty HTML elements
```

**Comment by CarsonLee27** [comment] 2016-04-15 03:42
I have the similar issue. But I think mine happen to all images.

**Comment by bactisme** [comment] 2016-04-15 09:53
Same Here

**Comment by fabianpimminger** [comment] 2016-04-15 11:36
Same here. Some articles get an empty <figcaption></figcaption> which results in an error.

**Comment by bobderrico80** [comment] 2016-04-15 15:12
Same problem here. Was actually going to create an issue about this today after trying a bunch of things yesterday and getting nowhere.

My original plan was to hook into `instant_articles_content` and search and replace `<figcaption.*?>.*?</figcaption>` with an empty string. This worked only if the content happened to already include a `<figcaption>` tag. I discovered that `<p><img ...></p>` is automatically wrapped in a `<figure>` with a `<figcaption>`, using the alt text as the inner text of the caption. This was happening after the filter, so it had no effect.

Next, I tried filtering search and replacing `alt=".*?"` with `alt=""`. This effectively removes the captions, but then Facebook flags the article for having tags with no inner text.

My current attempt is to hook into `instant_articles_featured_image` and change the instant article class before it is parsed to HTML, but it doesn't look like the `InstantArticle` has the method necessary to make this easy.

Ideally, what I would want to do was iterate over `InstantArticle.children`, find the `Image` objects, and set the `caption` property to null. This doesn't look like it's possible with the methods provided.

Any insights on how to solve this issue would be greatly appreciated.

**Comment by diegoquinteiro** [comment] 2016-04-15 16:16
Thank you all for the feedback.

I'll fix the alt to caption rule and release a new version by the end of the day.

@bobderrico80 you can use the 'instant_articles_transformed_object' filter to intercept the InstantArticle instance before it renders.

**Comment by bobderrico80** [comment] 2016-04-15 16:18
Okay, I've come up with a solution, not the most elegant but here goes:

```
use Facebook\InstantArticles\Elements\Image;
use Facebook\InstantArticles\Elements\InstantArticle;

add_filter('instant_articles_transformed_element', 'remove_captions_from_instant_articles');
function remove_captions_from_instant_articles($instant_article) {

    $mod_instant_article = InstantArticle::create();
    $mod_instant_article->withCanonicalURL(get_the_permalink());
    $mod_instant_article->withStyle('default');
    $mod_instant_article->withHeader($instant_article->getHeader());

    if (!is_null($instant_article->getFooter())) {
      $mod_instant_article->withFooter($instant_article->getFooter());
    }

    $mod_instant_article->addMetaProperty('op:transformer', 'facebook-instant-articles-sdk-php');
    $mod_instant_article->addMetaProperty('op:transformer:version', '1.0.3');

    $children = $instant_article->getChildren();
    $mod_children = array();

    foreach ($children as $child) {
      if ($child->getClassName() === 'Facebook\InstantArticles\Elements\Image') {
        $mod_image = Image::create();
        $mod_image->withURL($child->getUrl());

        if ($child->isLikeEnabled()) {
          $mod_image->enableLike();
        }

        if ($child->isCommentsEnabled()) {
          $mod_image->enableComments();
        }

        if (!is_null($child->getPresentation())) {
          $mod_image->withPresentation($child->getPresentation());
        }

        if (!is_null($child->getGeotag())) {
          $mod_image->withGeoTag($child->getGeotag());
        }

        if (!is_null($child->getAudio())) {
          $mod_image->withAudio($child->getAudio());
        }

        $mod_children[] = $mod_image;
        continue;

      }

      $mod_children[] = $child;
    }
```

Basically, what this does is filters the instant article right before rendering, makes a copy of it, iterates through its children, making a copy of each of those, removing the `caption` property when making a copy of an Image.

Again, not elegant, but it did the trick.

**Comment by bobderrico80** [comment] 2016-04-15 16:19
@diegoquinteiro excellent! As you can see, that's what I ended up doing. :-)

**Comment by fabianpimminger** [comment] 2016-04-15 16:24
I too think, that the alt-text should not be transformed into a caption as thats what the caption field in wordpress is for. And when a caption is set for an image, then wordpress uses figure and figcaption anyway. Alt-texts and captions are usually two different things in the wordpress world.

@bobderrico80 I guess we would have to modify the `rules-configuration.json`?

Maybe @diegoquinteiro can help?

**Comment by fabianpimminger** [comment] 2016-04-15 16:29
@diegoquinteiro thanks! 👍

I too think, that the alt-text should not be transformed into a caption as that's what the caption field in wordpress is for. Alt-texts and captions are usually two different things. And when a caption is set for an image, then wordpress uses figure and figcaption anyway - at least when using html5 markup. :-)

**Comment by diegoquinteiro** [comment] 2016-04-15 16:30
@bobderrico80 as @fabianpimminger noticed, you can also (and more easily) override the image rule using the Custom Rules JSON on the plugin settings page:

```javascript
{
    "rules" : [
        {
            "class": "ImageRule",
            "selector": "img",
            "properties": {
                "image.url": {
                    "type": "string",
                    "selector": "img",
                    "attribute": "src"
                }
            }
        }
    ]
}
```

The current built in rule in `rules-configuration.json` is wrong, including alt as caption:

```javascript
    ...
    {
        "class": "ImageRule",
        "selector": "img",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "src"
            },
            "image.caption": {
                "type": "element",
                "selector": "img[@alt]"
            }
        }
    },
    ...
```

**Comment by bobderrico80** [comment] 2016-04-15 17:30
Oh nice! That's much easier.

**Comment by bobderrico80** [comment] 2016-04-15 18:07
Actually, this doesn't seem to be working for me. Pulled out my original solution, and placed this in my custom rules:
```
{
    "rules" : [
        {
            "class": "ImageRule",
            "selector": "img",
            "properties": {
                "image.url": {
                    "type": "string",
                    "selector": "img",
                    "attribute": "src"
                }
            }
        }
    ]
}
```

My figcaptions are back.

**Comment by OPPtester** [comment] 2016-04-16 01:22
Please forgive my ignorance, but where exactly in the plugin settings can you add custom rules?  I see "enable custom embed code" but that is for Analytics!

**Comment by gabu69** [comment] 2016-04-16 01:23
@OPPtester ----> Enable custom transformer rules

Be sure you got the 2.7 version

**Comment by OPPtester** [comment] 2016-04-16 02:59
Got it thanks!

**Comment by demoive** [comment] 2016-04-18 16:21
@bobderrico80 I don't see anything wrong with the code snippet. I actually tested it locally and it successfully prevented the content of the `alt` attribute from being used as the `<figcaption>`. Effectively, it eliminates this section of the default ruleset:

```
...
            "image.caption": {
                "type": "element",
                "selector": "img[@alt]"
            }
...
```

**Comment by gabu69** [comment] 2016-04-18 16:42
@diegoquinteiro im sorry to say but even with those custom rules im experiencing some articles that show the ALT as caption 

Any other workaround?

**Comment by bobderrico80** [comment] 2016-04-18 17:48
@demoive that is correct, but in my case, I don't want any `<figcaption>` tags if there was no caption saved in the DB. Sometimes the content writers insert an image into their post with a caption (which Wordpress automatically formats as: `<figure><img ...><figcaption>...</figcaption></figure>`). But most of the time, they are not using captions, and just the plain `<img>` tag is being saved.

Changing the rule as you suggested still added the `<figcaption>` tags, but with no text. While this had the appearance of fixing the issue, FBIA threw warnings because I had HTML tags with no inner text.

I did figure out a solution. I forked the repo so that I could play around with the `rules-configuration.json` file directly. Then, I removed this rule altogether:

```
{
    "class": "CaptionRule",
    "selector": "img",
    "properties": {
        "caption.default": {
            "type": "string",
            "selector": "img",
            "attribute": "alt"
        }
    }
}
```

This prevents the caption rule from running on at all on `<img>` tags, as I only want it running when there is specifically a `<figcaption>` defined.

**Comment by demoive** [comment] 2016-04-18 23:35
@diegoquinteiro I've confirmed @bobderrico80's PR resolves the issue. I've also created #176 for general cleanup. Can you confirm?

**Comment by gabu69** [comment] 2016-04-19 00:05
So @demoive the solutionfor general people meanwhile would be:

{
    "rules" : [
        {
            "class": "CaptionRule",
            "selector": "img",
            "properties": {
                "caption.default": {
                    "type": "string",
                    "selector": "img",
                    "attribute": "alt"
                }
            }
        }
    ]
}

??? Or should we add something else?

**Comment by demoive** [comment] 2016-04-19 14:03
@gabu69, yes, adding your snippet to the **Custom transformer rules** option will "undo" what #174 removes. You can safely add it already so that when PR lands, there won't be a change in behaviour.

**Comment by gabu69** [comment] 2016-04-19 14:14
@demoive  its not working for me, implemented this rule, updated a post that has 2 figcaptions, even it has 8 images and all of them with alt tags, just 2 display figcaptions and after updating it it didnt remove the figcaption

**Comment by demoive** [comment] 2016-04-19 14:35
@gabu69 @fabianpimminger the issue with empty tags will be fixed once https://github.com/facebook/facebook-instant-articles-sdk-php/issues/31 lands. Please follow that thread if you want to be notified.

This issue can be closed.

**Comment by demoive** [comment] 2016-04-19 14:42
@gabu69 are the `figcaptions` you refer to just empty tags?

Could you provide more information about the source markup and the resulting Instant Articles markup? What would be really useful is the debug information/warnings at the bottom of the Edit Post screen within WordPress, particularly the two columns after clicking the "toggle debug information" link.

**Closed** 2016-04-19 17:00 UTC
Labels: bug

**Comment by bsgies** [comment] 2017-10-29 19:03
@demoive  Will you be able to help me about how to get rid of the captions? Example: https://image.prntscr.com/image/x8dg6eFXS_mCpsiiarys5Q.png
